### ISSUE TITLE
please remove the panopticlick EFF tracker protection domains unless they're actual trackers

### ISSUE THREAD

**Issue by jawz101** [AdAway/adaway.github.io#10]
I don't see the point of simply blocking these domains by hardcoding them in a list.
trackersimulator.org
eviltracker.net
do-not-tracker.org

If their purpose is to test certain fingerprinting techniques, why prevent them from doing that? You're effectively breaking the test of techniques that thousands of actual tracking companies use by blocking these 3 innocuous domains.

I can't find the right words to explain that.

I liken this to cell phone companies overclocking your phone when running benchmark apps. It helps your brand but we're actually trying to test something specific.

**Comment by dschuermann** [comment]
They have been added by the EFF themselves: https://github.com/AdAway/AdAway/pull/654

**Comment by jawz101** [comment]
Well, I added a comment to that old issue.  I still think it makes no sense to block these sites, even if ONE person from EFF thought it was a smart idea.
