### ISSUE TITLE
Amazon unable to connect

### ISSUE THREAD

**Issue by dfrost16** [AdAway/adaway.github.io#100]
Adway
![Screenshot_20200801-082850~2](https://user-images.githubusercontent.com/24663673/89095103-1d8ee980-d3e8-11ea-8d0a-5512998aeb6a.jpg)
: 5.0.5
Amazon unable to connect but website works just fine. I have to install adway cert to make it work

**Comment by jawz101** [comment]
Adaway doesn't have a certificate afaik.
And I would need to know exactly which Amazon entries cause the problem.  I have the Amazon app as well and it runs fine for me which means it's either that you're using additional lists or you're in a geographical area that connects to different servers than what I do and one of the few Amazon entries left are causing the problem.

Either way, you may want to try using the tcpdump tool in adaway to find the culprit
