### ISSUE TITLE
Whitelist CDN Domain

### ISSUE THREAD

**Issue by CyanoTex** [AdAway/adaway.github.io#107]
![Screenshot_20200807-121038818 (1).jpg](https://user-images.githubusercontent.com/62466866/89652017-22aad780-d8c5-11ea-9828-ba0abc61b764.jpg)

![Screenshot_20200807-121529007.jpg](https://user-images.githubusercontent.com/62466866/89652030-263e5e80-d8c5-11ea-915e-490f63e43b23.jpg)

**Comment by jawz101** [comment]
What is the reason for unblocking this?

**Comment by CyanoTex** [comment]
> What is the reason for unblocking this?  What app does it break for you?

It doesn't break an app but ``acrcloud.com`` uses this and it absolutely devastates their website from the looks of it.

**Comment by llacb47** [comment]
But the domain isn't in this list?

**Comment by jawz101** [comment]
considering the line of business and that the domain is found in Android apk's according to VirusTotal, I won't be removing this.

The site is for audio recognition in apps.  They market for recognizing people's voices, what they're watching on TV, and for marketing things.  That's exactly the sort of creepy stuff we don't want.
