### ISSUE TITLE
Unblock local DNS provider

### ISSUE THREAD

**Issue by KizunaH** [AdAway/adaway.github.io#110]
Domain: www.alidns.com (blocked by cname: 127.0.0.1 na61-na62.wagbridge.alibaba.tanx.com)
Description: this's the dns providers home page for view ip addresses and other details. If that keep blocked then people have to check foreign services instead similar quad9 dns, google dns etc.

**Comment by spirillen** [comment]
Hey @KizunaH 

(My personal opinion, not this repos)

Just by visiting there website, I don't feel it seems like a bad idea to switch DNS provider from this `$domain`

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +50 | \|\|github.com/_ws$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_ws` |
| +9 | ###gotop |  | alidns.com |  | dom | `https://alidns.com/` |
| +9 | \|\|sinajs.cn/open/api/js/wb.js | -- | alidns.com | 3 | script | `https://tjs.sjs.sinajs.cn/open/api/js/wb.js` |
| +5 | \|\|mmstat.com^$3p | -- | alidns.com | 3 | script | `https://log.mmstat.com/eg.js` |
| +4 | \|\|mmstat.com^$image | -- | alidns.com | 3 | image | `https://log.mmstat.com/v.gif?logtype=1&title=%E9%98%BF%E9%87%8CDNS&pre=&scr=1920x1080&spm-cnt=a2chw.13814944.0.0.13ab17609mL0Zn&category=&uidaplus=&aplus&yunid=&&trid=0b51178f15987015881186791ec4fb&asid=AQAAAAAUQEpfCRJYHQAAAAAgi6MnbmazhQ==&p=1&o=ubuntu&b=firefox80&s=1920x1080&w=gecko&ism=other&cache=c336658&lver=8.14.1&jsver=aplus_std&pver=0.7.11&tag=0&stag=-3&lstag=-1&_slog=0` |
| +4 | \|\|mmstat.com^$3p | -- | alidns.com | 3 | script | `https://log.mmstat.com/eg.js` |
| +2 | \|\|sinajs.cn/open/api/js/wb.js | -- | alidns.com | 3 | script | `https://tjs.sjs.sinajs.cn/open/api/js/wb.js` |
</details>

As they uses the very well known tracker `mmstat.com` <https://github.com/mypdns/matrix/issues/22>, Then it looks mostly to me like they are a tracking service (I don't understand any of those weird black things), And I'm taking a wild guess here, but if we read there privacy statement, they are probably going to tell us a lot about tracking by using there "service"

So if anyone can translate the site and even read and translate there user agreement/privacy it would be great.

**Comment by KizunaH** [comment]
@spirillen You cannot make such statements and what you can say about google DNS, open DNS, cloudflare DNS, neustar DNS and others? Those're not blocked at all.
Even alidns isn't a anonymous or extremely privacy friendly DNS provider but it's far better than most popular services.
