### ISSUE TITLE
False Positive: i.icomoon.io

### ISSUE THREAD

**Issue by Keyamoon** [AdAway/adaway.github.io#112]
i.icomoon.io is used for logging in to [IcoMoon](https://icomoon.io) accounts.  It's also used for hosting icon resources uploaded by IcoMoon users.

IcoMoon provides free vector icons along with a [free to use app](https://icomoon.io/app) for converting them to various formats including SVGs and fonts. Our services have nothing to do with ads or tracking users.

**Comment by jawz101** [comment]
removed.  thanks
