### ISSUE TITLE
Backup converter issue

### ISSUE THREAD

**Issue by PerfectSlayer** [AdAway/adaway.github.io#14]
Website converter doesn't work. I tried Edge, Firefox, Chrome on PC and Chrome on Android. Clicking buttons does nothing.
@edit:
I figure it out: it doesn't parse empty lines, you should fix that easily.
console log:
export:152 Uncaught TypeError: Cannot read property 'length' of null
    at convertToModern (export:152)
    at HTMLButtonElement.onclick (export:70)
@edit2:
but still there is some bug:
white *spotify.com* 
converts to: 
{
  "sources": [],
  "blocked": [],
  "allowed": [
    {
      "host": "tify.com*",
      "enabled": true
    }
  ],
  "redirected": []
}

_Originally posted by @vidmo91 in https://github.com/AdAway/AdAway/issues/1194#issuecomment-521620845_

**Comment by PerfectSlayer** [comment]
Hello @vidmo91

I fixed the _edit2_ issue but I can't reproduce the empty line issue.
Do you have an example I can test ? 

Thanks !

**Comment by vidmo91** [comment]
Here's my export file:
https://1drv.ms/u/s!ApyitC-UVfNMhpcs_316O00sU6G6HQ
I opened it with Astro File Explorer's text reader on phone and Notepad++ on Windows and copy-pasted all contents.

**Comment by PerfectSlayer** [comment]
Okay! Thanks for you file.
I finally found the issue: it was not an empty line issue of comment line issue.

Empty lines are skipped and then, comments are removed.
But a comment line is not empty, so not removed, then the comment is removed and the line becomes empty (so the parser fails).

It should be fixed right now (you can remove the comment line if you need to convert your file before the website update) 😉 

Thanks for taking time to write an issue about it 👍
