### ISSUE TITLE
Where to report ads?

### ISSUE THREAD

**Issue by milindgoel15** [AdAway/adaway.github.io#179]
I can't get where I should report ads displaying in apps that I am using. So wanted to know which is the correct place to report. Can anyone tell?

**Comment by milindgoel15** [comment]
So now I can just continue in this opened issue or there's something I have to do?

**Comment by AnXh3L0** [comment]
Yes, please continue here and report the ads.

**Comment by milindgoel15** [comment]
![Screenshot_20200919-203535_Sync.png](https://user-images.githubusercontent.com/45682747/93709311-14560980-fb5b-11ea-8a0f-52ea43b39cc1.png)

Idk how to extract logs. But this app is sync for reddit(beta), all the home ads are blocked but when we create new post, these ads come at bottom of the UI.

**Comment by AnXh3L0** [comment]
Not to be that guy but have you tried Slide for Reddit before @milindgoel15? It has no ads and it's fully open source (https://f-droid.org/en/packages/me.ccrama.redditslide/). About the Sync for Reddit one, we'd need some logs tbqh, but I suspect that's some cached ad.

Please try this. Close the app and force stop it, then clean its cache and reopen.

**Comment by milindgoel15** [comment]
Clearing cache worked 🎊.🎊

**Comment by AnXh3L0** [comment]
You can use the in-built AdAway logger.
