### ISSUE TITLE
sdk.split.io is needed for admin.webex.com - why is it blocked?

### ISSUE THREAD

**Issue by plusps** [AdAway/adaway.github.io#181]
admin.webex.com is a portal used by IT administrators to manage their company's users, licenses, services, etc. 

When "sdk.split.io" is blocked, the user management portion of the admin.webex.com does not work. 

If I whitelist "sdk.split.io", then I'm able to use it.

Why is "sdk.split.io" blocked?

**Comment by jawz101** [comment]
see https://github.com/StevenBlack/hosts/issues/1387

**Comment by plusps** [comment]
@jawz101 this doesn't exist in StevenBlack's hosts file anymore, it exists in this one, which is why I raised the issue here.

**Comment by jawz101** [comment]
I see it in StevenBlack's hostfile http://sbc.io/hosts/hosts and Adaway is a source list for StevenBlack's host file.

**Comment by plusps** [comment]
Has it been removed from the source list (adaway)?

**Comment by jawz101** [comment]
I do not understand your question.  If it is in the Adaway host file then it is in the Adaway host file.

Regardless, you are free to whitelist the entries in your ad blocker.

**Comment by plusps** [comment]
It has been removed from "StevenBlack's hostfile".

It has not been removed from the adaway host file.

@jawz101 Aren't you able to remove it from the adaway host file?

**Comment by jawz101** [comment]
I just pointed you to the steven black hosts file and showed you it's still there.

**Comment by plusps** [comment]
It's only there because it syncs over from the adaway hosts file.

If you remove it from the adaway hosts file, it will then be removed from
steven blacks.

**Comment by jawz101** [comment]
read my comments in the 2 tickets I mentioned.  I don't want to repeat myself.

**Comment by plusps** [comment]
Ohhh sorry. I misunderstood.

It would have been simpler and faster to say:

"Hi, I am @jawz101  -- I am the decider on this host file. I am making a choice to not remove sdk.split.io. Your choices are to either not use my host file, or whitelist sdk.split.io. Thanks and have a great day."

**Comment by jawz101** [comment]
Not a problem.  Sorry for the confusion.

**Comment by spirillen** [comment]
Hey @jawz101 interesting domain you've found there, however, I have not been able to locate, and thereby confirm, the use-cases you refer to on the $domains site.

Is it possible you could give a pointer in the right direction?
