### ISSUE TITLE
AdAway user map

### ISSUE THREAD

**Issue by PerfectSlayer** [AdAway/adaway.github.io#182]
Hello @AnXh3L0 👋 

I hope you doing fine.
I did some experiments with the web server access logs and I tried to create a map of the AdAway users. Here is the result:

![image](https://user-images.githubusercontent.com/1766222/95673004-48927800-0ba5-11eb-8940-14d723820159.png)

It is based of the beta users only (for now) and updated every month.
It's a Javascript based vector (heat)map. Quite simple to integrate (one div and few js file).

What do you thing of integrating it on the website to show what the app community represents?

Kind regards

**Comment by AnXh3L0** [comment]
Hey @PerfectSlayer, sure, you can send me the files and I'll add the map.

**Comment by spirillen** [comment]
I'll suspect as darker the red color is, is equal fewer downloads? as they are more vulnerable for IP tracking?

**Comment by PerfectSlayer** [comment]
Nope, darker means more users. 
I agree red is might not as be clear as I first though...

Here is the sample html file I use to create the map:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User map</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jvectormap/2.0.5/jquery-jvectormap.css"
        integrity="sha512-1ZwE8kCr0CknYsK+JYHqxnFqCZ2c17AJ6uTVf6me8UFCZJPE12ujWxnspvRJUb/zciTQ2D58PkJHQk5PLSYJ4Q=="
        crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
    <script src="https://jvectormap.com/js/jquery-jvectormap-2.0.5.min.js"></script>
    <script src="https://jvectormap.com/js/jquery-jvectormap-world-mill.js"></script>
</head>

<body>
    <div id="world-map" style="width: 800px; height: 600px"></div>
    <script>
        let total = 1;
        let data = {};
        fetch('https://app.adaway.org/users.json')
            .then(response => response.json())
            .then(json => {
                data = json;
                $(function () {
                    $('#world-map').vectorMap({
                        map: 'world_mill',
                        series: {
                            regions: [{
                                values: data,
                                scale: ['#ffc7c7', '#a30000'],
                                // scale: ['#C8EEFF', '#0071A4'],
                                normalizeFunction: 'polynomial',
                                // legend: {
                                //     horizontal: true,
                                //     title: 'Color'
                                // }
                            }]
                        },
                        onRegionTipShow: function (e, el, code) {
                            let percent = data[code];
                            if (percent === undefined) {
                                percent = 0;
                            } else if (percent === 0) {
                                percent = '<0.1';
                            } else {
                                percent = Math.round(percent * 10) / 10;
                            }
                            el.html(el.html() + ' (' + percent + '% of all users)');
                        }
                    });
                });
            });
    </script>
</body>

</html>
```

We can easily adjust the color, show a legend, etc...
@AnXh3L0 I just push the backend update so you are free to experiment with the real data!

Here is [the documentation](https://jvectormap.com/documentation/) and here are [some samples](https://jvectormap.com/examples/world-gdp/). My primary idea was to make something light and simple to show AdAway has a lot of friends everywhere 😄  You can customize it to make it fit better the website if you want to.
And I think it will be fun to see the map evolve when 5.x hits the stable channel 😉

**Comment by spirillen** [comment]
You caught my irony :smiley: 

But here is a tracking issue hidden you should remember to fix 
```html

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jvectormap/2.0.5/jquery-jvectormap.css"
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://jvectormap.com/js/jquery-jvectormap-2.0.5.min.js"></script>
    <script src="https://jvectormap.com/js/jquery-jvectormap-world-mill.js"></script>
```

All external scripts should be self hosted (own domain)... third party scripts are always bad for privacy :reminder_ribbon:

**Comment by AnXh3L0** [comment]
@spirillen, ofc, we always selfhost the scripts, I wouldn't rely on 3rd parties for that ;)

**Comment by PerfectSlayer** [comment]
I literally was testing the map with an html file on my desktop.
It was not intended to go live as is. I let @AnXh3L0 the pleasure to integrate it as he pleases 😊

**Comment by AnXh3L0** [comment]
@PerfectSlayer we're unfortunately getting CORS errors related to the json file, maybe I should also host in the repo itself instead of fetching from the link?
![image](https://user-images.githubusercontent.com/25004151/95762098-8aa6e100-0cad-11eb-8650-0e6fc9564b44.png)

**Comment by PerfectSlayer** [comment]
Good catch! I'm working on it...
In fact, you can't really host it on the repo as the json file is actually a PHP file that check data cache.
If present, it will redirect to the cached data. If not, it will compute it then redirect.

It is not a static json file you can store 😅 
I will keep you posted as soon as I get CORS working!

**Comment by AnXh3L0** [comment]
I actually tested it with the output file from the link, and it worked just fine. That would need a monthly file replace though, but it's the quickest way out.

**Comment by PerfectSlayer** [comment]
Ok, I fixed the backend (/users.json) and the json repo (/users/yyymm.json file)
It should be fine for now. I still need to polish some stuff but at least you can play with it 😉

**Comment by AnXh3L0** [comment]
Works fine now, thanks 👍

**Comment by PerfectSlayer** [comment]
Looks good! 👌 
Have you tried with a white background (the same as the web page)?

I guess you can change it from the map parameters: https://jvectormap.com/documentation/javascript-api/jvm-map/
Maybe something like:
```js
$('#world-map').vectorMap({
  map: 'world_mill',
  backgroundColor: '#fff',
  series: {
```
