### ISSUE TITLE
 AdAway filter breaks different main websites

### ISSUE THREAD

**Issue by mathieuruellan** [AdAway/adaway.github.io#184]
Several websites are using **cdn.tagcommander.com** to host js files. Puting it in black list, makes interfaces not working well without error message.
My last personnal experience was with this user interface: https://www.malakoffhumanis.com/ 
I can see in pihole forums similar problems with ubisoft store or laposte.fr.

**Comment by jawz101** [comment]
removed.  Though I don't know if people would want it removed https://www.commandersact.com/en/  like their whole product is about marketing shit.  They're in the top 35,000 most popular DNS lookups in the world.

https://www.commandersact.com/en/

https://community.commandersact.com/tagcommander/getting-started/setup-guides/android

I'm not French so I guess it doesn't affect me.

**Comment by spirillen** [comment]
Don't worry @jawz101 I haven't removed this shit. As you say your self, if people like access to this privacy pirate, they have to whitelist it them self as it should be.

I'll actually recommend you'll add it back and then tells people to whitelist it from there blacklist them self, as you have warned them by now.

**Comment by jawz101** [comment]
@spirillen I've been meaning to reach out to you.  I've recently decided to pass list maintenance on to someone.  Would you be interested?

**Comment by mathieuruellan** [comment]
Thanks for taking time to answser. Your arguments are fully admissible/understandable.
Now they are aware of that.

**Comment by spirillen** [comment]
> @spirillen I've been meaning to reach out to you. I've recently decided to pass list maintenance on to someone. Would you be interested? I think you have a similar regard for what is and is not desirable.

Are you on keybase?? or could you jump on the chat on mypdns.org? 

This is coming as a surprise to me.

**Comment by jawz101** [comment]
oh I'm not on keybase.  Not even sure what that is.  but yeah lol.  So whaddya think?

**Comment by spirillen** [comment]
Hey @jawz101 

I'm not against the idea, and I'm flattered you are thinking on me :smiley: 

But in the reality, there are more than one thing to think of, if I should integrate yet another project, which should happens until the [@matrix-rocks](https://www.mypdns.org/project/view/15/) was seeing the sun-rise as mixing hosts formatted list with RPZ syntax (Wildcard blocking) is a rather time consuming approach on a manual basis.

The other concern I have to just take over this project is your source for finding new records, as I don't use any mobile devices for online activities. As I recall it you are using you firewall to extract [NOD](https://github.com/mypdns/NOD)'s 

Would users accept that the issue board would be transferred to my phabricator issue board at https://www.mypdns.org/ to protect users data and privacy integrity?


NOTE:

To let you know I'm seriously consider your offer, I have made an issue here. <https://www.mypdns.org/T2632>

However you should get the signup so I can add you to the issue and let you see it, as some of my question is not yet ready for the public.

A question like this also deserves it's own thread and not as detouring the OP's question.

PS: 
Up front I'll will accepts being "santas little" helper with write/push access to this repo, to help maintaining it.

**Comment by jawz101** [comment]
I appreciate your feedback.  It sounds like your focus is on another component of DNS resolution with the mypdns project.

I may also reach out to some members of the Exodus Privacy Project or a couple of other people I have in mind that have a focus particularly on mobile privacy

**Comment by spirillen** [comment]
> I may also reach out to some members of the Exodus Privacy Project or a couple of other people I have in mind that have a focus particularly on mobile privacy

This sounds good :smiley: more opinion's is always better, and will lay a the basic for weather a record should be or not.

However I have actually already initiated the first steps, to integrate this project and awaiting @funilrys response, as it will relay on a cooperative work with him to build the [centralized domain database](https://www.mypdns.org/T2686) which is directly integration with [PyFunceble](https://github.com/funilrys/PyFunceble)

In short that your honored me by offering me to become your successor is actually not that far from a plan already in action, it's more that we would have to rush up some of the sub-projects :smiley: 

> It sounds like your focus is on another component of DNS resolution with the mypdns project.

True, as you have a wider option to actually minimize the bare number of records in the RPZ vs hosts-, flat-formatted files and a broader variety for manipulating the responses set by the RPZ, this is my child, however I have always had the hosts formatting in mind when i put up something as I know there will be a transaction time before other will follow over to the way more modern RPZ.

A example of this is I can shrink https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist 1.6 million records to less than 600.000 with the DNS RPZ

> particularly on mobile privacy

This is a integrated part of the matrix.rocks project Central Domain Database. And different crawlers are on the drawing board (idea plan)

## Questions
@PerfectSlayer, @jawz101:  Is there a particular reason to why records are grouped by domain.tld in the hosts file?

@PerfectSlayer: Is it possible to integrate ordinary RPZ/dns records into the java dns in android?
The question, is it the time to incorporate something else, if there will be a switch anyway? (output format)

## End note:
I think you should invite the other good people you have in mind into this talk, it can only improve the feedbacks and numbers of idea's. A given project is never better than the numbers of feedback's for improving things, I work one way, other good folks works in another way and we should have room and consideration for all.

This is a few thoughts for now.

**Comment by jawz101** [comment]
I asked to group the list that way for readability.  Ex: so amazon.com, amazon.eu, amazon.jp are clumped together.

**Comment by PerfectSlayer** [comment]
>  I may also reach out to some members of the Exodus Privacy Project or a couple of other people I have in mind that have a focus particularly on mobile privacy


> This sounds good 😃 more opinion's is always better, and will lay a the basic for weather a record should be or not.

Agreed! It's been a long time I want to discuss with team too.

> Is it possible to integrate ordinary RPZ/dns records into the java dns in android?

Hum, yes and no. AdAway is basically an hosts file manager and hosts file does not support this format (if I'm right).
But the app recently provides a new ad block method for non root devices based on the Android VPN API. From here, I guess I could handle the RPZ/dns records but it won't make it for the default hosts file based ad block method.

> I think you should invite the other good people you have in mind into this talk, it can only improve the feedbacks and numbers of idea's.

I'm also in favor to discuss with the community what can be done together  🤝😃

**Comment by spirillen** [comment]
Now it's up to this request in https://github.com/AdAway/AdAway/issues/2332 if @PerfectSlayer & co accept this feature, I'm your new Admiral.

I would however still endure if you could find some good folks on the exodus project to become captains and helmsmen to keep the democratic process for whether a record should be on the general or a grey-list rule-set.

There should also always be a backup plan in case anything goes wrong with anyone assigned to this project.
