### ISSUE TITLE
adaway hosts file breaks iFunny on android

### ISSUE THREAD

**Issue by nahdoubtit** [AdAway/adaway.github.io#186]
using the adaway.org/hosts.txt file now breaks iFunny on android, using their mobile app. disabling adaway completely fixes it, as well as disabling JUST the adaway.org host. No other hosts are enabled besides the default ones (host-file.net and pgl.yoyo). I tried enabling logging dns requests but it's not showing any results.

**Comment by jawz101** [comment]
I guess I'll remove those.  I have no idea what that is but I guess if you want it you can have it.
