### ISSUE TITLE
False positive: rebtelsdk.pubnub.com

### ISSUE THREAD

**Issue by S-a-l-a-d** [AdAway/adaway.github.io#187]
Grab seems to be using Sinch's platform, which utilizes another platform called PubNub. And blocking this domain breaks the in-app VoIP feature.

Here is the app homepage: https://www.grab.com

**Comment by spirillen** [comment]
@S-a-l-a-d then grab is a broken piece of junk, you should contact there support dev team and tell them they have added spy-, location-, trackware to there product, and as a costumer who is concerned about your privacy, the program isn't working.

Removing [pubnub](https://www.mypdns.org/T2539) is like removing every domains in this or any other blacklist.

**Comment by jawz101** [comment]
I'm reading up on it.  Looks like pubnub is mostly used for realtime communication.  There is some association w/ push notifications and geolocation but if it's primarily for communications and, in this example according to reddit posts, it breaks communication w/ your driver.  I think it's reasonable not to break that functionality.

**Comment by spirillen** [comment]
The thing is, you are as such right about the mostly used for good things, but the reason I have it listed is I've found it for ad-targeting and geo locating on websites, why I've found it in the first place, unfortunately I've forgot to add the ref for where it was.

So keeping it on the Exodus list is good it probably a good tradeoff. I would call it a grey area...

**Comment by jawz101** [comment]
Oh it's a gray area.  But I try to keep the Adaway list as strictly mobile app as possible and, when it comes to its mobile app ask, the case studies look like they're mainly using this for communications and fleet management.
