### ISSUE TITLE
cdnapisec.kaltura.com and cfvod.kaltura.com broke Canvas LSM Kaltura videos

### ISSUE THREAD

**Issue by xyb994** [AdAway/adaway.github.io#188]
cdnapisec.kaltura.com
cfvod.kaltura.com

Above two kaltura subdomains seem to be used by [kaltura](https://corp.kaltura.com/education-video-platform/lms-video-integrations/) in [Canvas LMS](https://www.instructure.com/canvas/). With them blocked, users are not able to view kaltura videos on Canvas LMS. They were [added 8 days ago to adaway](https://github.com/AdAway/adaway.github.io/blame/2a01faacbf943026aaeb63315451aa4da92d94c2/hosts.txt#L6729) and brought into [StevenBlack](https://github.com/StevenBlack/hosts/blame/b72648459c75ab7a6e5975cd984c169eb586bf6e/data/adaway.org/hosts#L6741)

**Comment by jawz101** [comment]
removed.  thank you

**Comment by llacb47** [comment]
`cdnsecakmi.kaltura.com` is also a false positive.
