### ISSUE TITLE
Breakage on amway.si due to tags.tiqcdn.com

### ISSUE THREAD

**Issue by crssi** [AdAway/adaway.github.io#189]
Login at `https://www.amway.si/` is broken due to `tiqcdn.com` and `tags.tiqcdn.com`

Cheers

**Comment by jawz101** [comment]
I'll remove tiqcdn.com but

**Comment by llacb47** [comment]
but what?

**Comment by crssi** [comment]
Thank you @jawz101

Cheers

**Comment by jawz101** [comment]
@llacb47 typo
