### ISSUE TITLE
Unblock e.infogram.com

### ISSUE THREAD

**Issue by onovy** [AdAway/adaway.github.io#196]
Hi, please unblock: e.infogram.com

That URL is used for infographics embeding on news servers. Example:

https://e.infogram.com/df0c2af8-5119-4d11-844a-a05fb952283a?src=embed

here:

https://www.seznamzpravy.cz/clanek/prvni-pes-rizikove-skore-v-cesku-je-70-v-praze-je-o-desitky-nizsi-129746

**Comment by jawz101** [comment]
removed.  thanks

**Comment by spirillen** [comment]
Shouldn't this issue have been closed??
