### ISSUE TITLE
Survey over mail blocked

### ISSUE THREAD

**Issue by crssi** [AdAway/adaway.github.io#201]
Link to survey sent over email is `https://bcdtravel.iad1.qualtrics.com/jfe/form/SV_cI1RctlA8nQr2Xr?Q_DL=Mx3SFBZAXQ5iR1g_cI1RctlA8nQr2Xr_CGC_pVEksAEj3m5m8Mm&Q_CHL=email`.

Rule `||iad1.qualtrics.com^` prevents opening the survey.

Cheers

**Comment by jawz101** [comment]
Thanks.  I'm going to remove all of the entries for that domain once I get to a desktop.  Every time I see "tic" or "tric" in a domain name I just assume it wants to measure something about me... but sometimes it's actually consensual which this looks like the case.

Why does your username look familiar?  It feels like you do Android development or something.

**Comment by crssi** [comment]
Do not know. 😄 
Our path has crossed a few times, I guess, at pants and web-api-manager for sure.

Thank you and wish you best

**Comment by jawz101** [comment]
that must be it.  Take care
