### ISSUE TITLE
remove anvato

### ISSUE THREAD

**Issue by llacb47** [AdAway/adaway.github.io#203]
anvato is a cdn.

Added in https://github.com/AdAway/adaway.github.io/commit/1757a0a12d783ec7c47477f07a40b0dfd9fee206#diff-439cb660fd781cb9fe5038b20c8de144aa5070b1d7c790e25e85d5436e867822R2135

See https://github.com/lightswitch05/hosts/issues/89

breaking videos here:

```
https://www.wsav.com/crime-safety/police-investigate-suspicious-death-near-jefferson-35th-streets/
https://www.fox5atlanta.com/news/coronavirus-restrictions-by-state-what-you-need-to-know
https://www.wfla.com/news/pasco-county/likely-over-50-feet-deep-pasco-depression-threatens-nearby-businesses/
```

**Comment by llacb47** [comment]
@jawz101

**Comment by jawz101** [comment]
chill.  I had to test and search to see which subdomains were the problem.  It's still a company with a monetization platform and not knowing which subdomains are specifically used for cdn stuff versus the monetization stuff takes a little bit of research.

**Comment by llacb47** [comment]
Thank you.
