### ISSUE TITLE
Broken page due to rule widgets.pinterest.com

### ISSUE THREAD

**Issue by crssi** [AdAway/adaway.github.io#204]
STR:
1. Visit site `https://www.zadovoljna.si/lepota/zenske-frizure/zenske-frizure-2019-10-frizur-za-kratkolaske-ki-bodo-hit-jeseni.html`
2. Click on "OMOGOCI PISKOTKE" button to allow cookies... see 
![image](https://user-images.githubusercontent.com/17024151/102331485-d2363b80-3f82-11eb-97ff-2d4d7bee2d2c.png)

Expected results: When not blocking `widgets.pinterest.com` we can see pictures
Actual results: When we block `widgets.pinterest.com` there is missing content

Thank you and cheers

NOTE: By observing our household traffic logs for last couple of months, the `widgets.pinterest.com` is used rarely, but when it does, there is a breakage. This rarity make me think that it is not really used for ads or tracking purposes.

**Comment by jawz101** [comment]
removed.  thanks

**Comment by spirillen** [comment]
@crssi wrote:

> NOTE: By observing our household traffic logs for last couple of months, the widgets.pinterest.com is used rarely, but when it does, there is a breakage. This rarity make me think that it is not really used for ads or tracking purposes.

Unfortunately this domain is actually doing a lot of tracking.... (Just a note)

**Comment by crssi** [comment]
Here I have about 30 devices, all kind of browsing behavior, from youngsters to elders.
In the last month I have less than 10 requests in the DNS logs.
I believe you that there might be a lot of tracking from your perspective, but here I would not say so.

**Comment by spirillen** [comment]
Without starting a long discussion about this, and that I haven't transferred any records about this domain to my logs.

I can even from the top of my head remember a lot of debate of whether this was a domain to be blocked or not in various repos.

> I believe you that there might be a lot of tracking from your perspective, but here I would not say so.

Well there is going a lot of tracking on, personally I don't like it, what you think of it or at which level you are willing to accept is up to you. I have never and will never challenge or comment your choice.

Facts is facts, what you choose to do with it, that is your and your choice only. Should we please keep it to the facts and subject in the future?
