### ISSUE TITLE
Unable to download from any Hosts sources

### ISSUE THREAD

**Issue by TimRude** [AdAway/adaway.github.io#206]
Older rooted tablet running Android 4.4.2 (KitKat). Installed AdAway 4.3.6 from F-Droid.

When I try to Enable Ad-Blocking to download the hosts files, it fails to download any. I haven't changed the default hosts files.

I can open the Chrome browser and manually go to https://adaway.org/hosts.txt and I can download the hosts.txt file. So I know it's not an internet issue.

Any ideas why AdAway can't download the hosts files itself?

**Comment by spirillen** [comment]
You should probably post your issue here <https://github.com/AdAway/AdAway/issues> instead, as this is only for the list, the mentioned link is to the program AdAway
