### ISSUE TITLE
Remove usersnap from the list

### ISSUE THREAD

**Issue by angelsenra** [AdAway/adaway.github.io#208]
Usersnap is a tool for users to give feedback about the website. It does not track users unless they write a message and click submit. It also contains no advertisements.

PR is ready at #207 should it be admitted.

Thanks, and please reply if you have any questions about what Usersnap does or how much info it collects about users. I believe it is not to be considered invasive or a threat to privacy since it only collects what the user is willing to say about the website.

**Comment by jawz101** [comment]
done
