### ISSUE TITLE
Clickdimensions block prevents access to customer file

### ISSUE THREAD

**Issue by Mandrake66** [AdAway/adaway.github.io#209]
I receive a link to a customer's member list once a month, and it resolves to download the file from file-us.clickdimensions.com - which was getting blocked with "unable to reach site" or something of the like.  After a few months of frustrations I finally saw a suggestion that it might be my hosts file.  I blanked hosts and voila, I could get to the download.  I searched my hosts file (I use the one from github dot com/StevenBlack/hosts and found the clickdimensions section where the file-us bit was getting blocked.  Hashtagging this line let me get the file, but I will have to do this each time I refresh the hosts file.

So the question - this host-based blocking prevents access to legitimate files, but is it a case of the bad outweighing the good by enough that it needs to be blocked in general?

**Comment by spirillen** [comment]
> @Mandrake66 manfoyd wrote
> So the question - this host-based blocking prevents access to legitimate files, but is it a case of the bad outweighing the good by enough that it needs to be blocked in general?

This is a very open question, and the answer will completely relay on who answering it.

My personal answer to is clear, if the domain hosts any form of unwanted ware, it is blocked until it have removed the badware.

The real answer to your question, well, you need to hold your own whitelist, which you runs against any dumb hosts file imports. Depending on what OS you are using, there are a number of ways to upgrade to use RPZ vs dumb hosts files. You can read a non scientific comparison here <https://www.mypdns.org/w/performance_test_of_hosts_file_vs_dns-recursors/> and you'll soon get a desire to upgrade :smile: :smirk:

**Comment by jawz101** [comment]
removed some of the entries not associated with mobile app traffic
