### ISSUE TITLE
Request to whitelist mazu.3g.qq.com

### ISSUE THREAD

**Issue by terrytw** [AdAway/adaway.github.io#210]
Hello everyone, 

I would like to submit a request to whitelist mazu.3g.qq.com.

Blocking this sub-domain will render the "QQ Security" app (com.tencent.token) completely unusable.

A little context: "QQ Security" is an app that lets users modify the security related settings for their QQ account. (QQ is one of the two major instant messaging service from Tencent, the other being Wechat.)

When mazu.3g.qq.com is blocked, user cannot log into "QQ security" app at all, app will come back with an error 201 notification. If you cannot login, this app is completely useless.

Cheers!

**Comment by jawz101** [comment]
Will remove.  Thank you for letting me know.
