### ISSUE TITLE
Remove Cleverpush service

### ISSUE THREAD

**Issue by BjoAce** [AdAway/adaway.github.io#211]
Cleverpush is used in some apps & websites to provide push messages - not only ads. Modern browsers & OS ask users before allowing them.
Please remove it's domains. Thx.

```
# [cleverpush.com]
3474 | 127.0.0.1 api.cleverpush.com
3475 | 127.0.0.1 geoip-api.cleverpush.com
3476 | 127.0.0.1 static.cleverpush.com
3477 | 127.0.0.1 statistacomdev.cleverpush.com
```

**Comment by jawz101** [comment]
They will not be removed.  Thank you
