### ISSUE TITLE
Allow mobilepartner.avcdn.net.edgekey.net

### ISSUE THREAD

**Issue by cbwee** [AdAway/adaway.github.io#212]
This domain, mobilepartner.avcdn.net.edgekey.net, is used for updating the security scan definitions(Avast), in XIaomi phones' MIUI.

So it needs to be allowed, to be able to update the security scan definitions in Xiaomi phones.

**Comment by spirillen** [comment]
Isn't it XIaom phones that are well known for being spyware phones? (honest question)

**Comment by cbwee** [comment]
> Isn't it XIaom phones that are well known for being spyware phones? (honest question)

I know, it's also well-known for having ads in system apps, but I have to keep using MIUI to keep the bootloader locked, and the Security app in MIUI uses Avast definitions for scanning.

I have already debloated my phone with adb.

If the Security app is uninstalled using adb, this will cause bootloop in MIUI (Xiaomi) phones, so I need to keep it.

So when that domain for the Avast definitions is blocked, the Security app will always shown an error "update failed".

**Comment by cbwee** [comment]
I'm now closing this issue.
