### ISSUE TITLE
Few domains to block

### ISSUE THREAD

**Issue by Alex-B-Buf** [AdAway/adaway.github.io#215]
Hello,

Found a few domains from which comes ads on the tablet of my child.
Mostly video ads from children's games from GPlay.

```
ad.vidver.to
ad.vidverto.io
adolf.tv
tutoads.tv
target2sell.com
```

Ads is gone after add these domains to custom list.
Just wanted to share, in case you want to add them to main list.

**Comment by spirillen** [comment]
I can confirm:

  - `vidverto.io` <https://www.mypdns.org/T4192>
  - Will update in a bit, just got disturbed to other side...

**Comment by jawz101** [comment]
damn.  I missed one.  I did a recent add yesterday from watching my DNS logs on NextDNS.  I was hoping I caught all of the legit stuff.  Removing now and thank you for reporting.

**Comment by spirillen** [comment]
Hey @jawz101, what did you find about the 2 domains I couldn't find anything about?

**Comment by jawz101** [comment]
I just took their word for it.  I couldn't find anything about it but it sounded like something I won't miss and the others seem legit.

**Comment by spirillen** [comment]
it should be related to GPlay according to OP's post... I now I think about it, do you have anything about them in exodus??

**Comment by Alex-B-Buf** [comment]
> * `vidver.to`

Found in dns logs with subdomain: `ad.vidver.to`
It looks like this is an additional domain of `vidverto.io` and `ad` subdomain hints that this is an ad, so I decided to block it.

> * `adolf.tv`

Found in dns logs with subdomain: `get.adolf.tv`
After blocking this domain, some of the video ads disappeared.

Domains very similar to tutoads one: `get.adolf.tv tracy.adolf.tv` `get.tutoads.tv tracy.tutoads.tv`

Googled domain, found similar game here:
https://aapks.com/apk/hannah-s-high-school-crush/

From "Interesting Strings" block:
https://get.adolf.tv/v2/load/
https://tracy.adolf.tv/v1/install?

@jawz101 I'm sorry, just realized that root domain is not enough for the application, we also need subdomains

From logs:

```
adolf.tv
get.adolf.tv
tracy.adolf.tv

tutoads.tv
tracy.tutoads.tv
get.tutoads.tv
cdn.tutoads.tv

target2sell.com
api.target2sell.com
serv-api.target2sell.com
static.target2sell.com
```

**Comment by spirillen** [comment]
Thanks for your feedback, there are actually some good stuff in under the `Interesting Strings` section

From the top of my head I find these know ads/trackers:

```
http://tracker.tutotoons.com/ad_tracker_custom.php?
http://www.google-analytics.com/collect
http://www.google-analytics.com/collect?
https://adc3-launch-staging.adcolony.com/v4/launch
https://adc3-launch.adcolony.com/v4/launch
https://app-measurement.com/a
https://init.supersonicads.com/sdk/v
https://pagead2.googlesyndication.com/pagead/gen_204?id=gmob-apps
https://pubads.g.doubleclick.net/activity;dc_iu=
https://pubads.g.doubleclick.net/activity;xsp=
https://wd.adcolony.com/logs
https://www.googleadservices.com/pagead/conversion/
https://www.supersonicads.com/mobile/sdk5/log?method=
https://www.supersonicads.com/mobile/sdk5/log?method=encodeAppKey
https://www.supersonicads.com/mobile/sdk5/log?method=encodeAppUserId
https://www.supersonicads.com/mobile/sdk5/log?method=extraParametersToJson
https://www.supersonicads.com/mobile/sdk5/log?method=htmlControllerDoesNotExistOnFileSystem
https://www.supersonicads.com/mobile/sdk5/log?method=injectJavaScript
https://www.supersonicads.com/mobile/sdk5/log?method=noProductType
https://www.supersonicads.com/mobile/sdk5/log?method=webviewLoadBlank
https://www.supersonicads.com/mobile/sdk5/log?method=webviewLoadWithPath
```

Other suspicious

```
https://ads.api.vungle.com/
https://ads.staging.superawesome.tv/v2
https://ads.superawesome.tv
https://ads.superawesome.tv/v2
https://ads.superawesome.tv/v2/safead
https://adstrck.tutotoons.com/v2/error
https://analytics.kidoz.net/parents/KidozRestMobile.php
https://get.adolf.tv/v2/load/
https://mobile-static.adsafeprotected.com/avid-v2.js
https://mobilelogs.supersonic.com
https://outcome.supersonicads.com/mediation/
https://px.moatads.com/pixel.gif?e=0&i=MOATSDK1&ac=1
https://track.atom-data.io
https://tracker.tutotoons.com/ad_tracker_custom.php?
https://tracy.adolf.tv/v1/install?
https://www.adobe.com/airgames/4/
https://www.adobe.com/airgames/5/
https://www.adobe.com/gamepreview/?game=notification/notificationClicked.html_
```
Just from skimming the list....  that a lot of bad and potentially bad stuff.

But I don't understand why there should be a call to `http://www.example.com`?? that doesn't make sense to me.

How many of these have you seen in your log @Alex-B-Buf and how many can you confirm @jawz101 ??

I'll have a lookup in my archives tomorrow, as some of these might require some more investigation from my side to be classified for transparency and backlog as also mentioned by @Somebodyisnobody in <https://www.mypdns.org/T3681#59336>

**Comment by jawz101** [comment]
example.com is probably used in some generic template file in the code somewhere.  Sometimes example.com is used to either test something is up or for a developer to demonstrate something

https://en.wikipedia.org/wiki/Example.com

**Comment by spirillen** [comment]
> example.com is probably used in some generic template file in the code somewhere. Sometimes example.com is used to either test something is up or for a developer to demonstrate something
> 

:smile: I know about the RFC:2006 (example.(org|net|com)) but thanks, my wondering is, why is should be found inside spyware... what's is purpose there.
.... Is it used for some in-code network testing? or??

![image](https://user-images.githubusercontent.com/44526987/109735230-b24a0780-7bc2-11eb-8caa-880516c4c9a9.png)


example.org.zone: <https://www.mypdns.org/P37>
