### ISSUE TITLE
False positive: tvc3.investingapp.net

### ISSUE THREAD

**Issue by Alex-B-Buf** [AdAway/adaway.github.io#216]
This domain returns graphs.
For example: without params in desktop browser it is a EUR/USD chart http://tvc3.investingapp.net/

It is used for stocks charts in https://play.google.com/store/apps/details?id=com.fusionmedia.investing app
And mobile version of site: https://m.investing.com/indices/us-spx-500-advanced-chart (chart in horizontal mode)

**Comment by jawz101** [comment]
damn.  I missed one.  I did a recent add yesterday from watching my DNS logs on NextDNS.  I was hoping I caught all of the legit stuff.  Removing now and thank you for reporting.
