### ISSUE TITLE
Remove accesstrade.vn & accesstrade.com.vn

### ISSUE THREAD

**Issue by bigdargon** [AdAway/adaway.github.io#217]
Accesstrade is a deep link service. Some posts share a purchase, insert a deep link to hide the real address.

Example: https://go.isclix.com/deep_link/4608706208340350795?url=https%3A%2F%2Fshopee.vn%2Fflash_sale%3FfromItem%3D6264911552%26promotionId%3D2009330817

Direct to: https://click.accesstrade.vn/adv.php?url=https%3A%2F%2Fshopee.vn%2Funiversal-link%2Fflash_sale%3Futm_campaign%3D-%26utm_content%3D%7Bclickid%7D-%7Bpsn%7D-322--%26utm_source%3Dan_17104620000%26utm_medium%3Daffiliates%26fromItem%3D6264911552%26promotionId%3D2009330817&at_unique_id=J_AV1HEjMjVdpRyMVWasZ_nxat&rk=00063d000x2t&at_source=deep_link

In addition, blocking two domains `accesstrade.vn` & `accesstrade.com.vn` when using NextDNS will also block subdomains.

Some of the addresses I have captured

```
http://service-api.accesstrade.vn/js/v2/d2c.js
http://static.accesstrade.vn/js/trackingtag/tracking.min.js
http://partner.accesstrade.vn/static/js/haravan_tracking_v1.js?shop_id=5009001992508726873&is_lastclick=0
```

So I suggest blocking the following domains

```
ad.accesstrade.vn
partner.accesstrade.vn
service-api.accesstrade.vn
static.accesstrade.vn
track.accesstrade.vn
```

**Comment by jawz101** [comment]
thank you.  I'll add asap

**Comment by bigdargon** [comment]
The domains you should remove

```
accesstrade.com.vn
fast.accesstrade.com.vn

accesstrade.vn
click.accesstrade.vn
```

**Comment by spirillen** [comment]
> The domains you should remove
> 
> ```
But deeplinking / urlshortening / target obfuscation is bad. First off there is a hole security risk as you don't know where you ends up, malware, spyware etc., Next most of this is financed thought selling your click-tracking data.

So actually adding them, seems right to me.


Second to my thought, then you should have a look at the commit https://github.com/AdAway/adaway.github.io/commit/0c9aef4af8003db2959a69495867e676a6c0504a, Then you'll notice that @jawz101 added the domains you suggested

```
ad.accesstrade.vn
partner.accesstrade.vn
service-api.accesstrade.vn
track.accesstrade.vn
```

And for common security kept
`accesstrade.vn`

Under my common perception, I'll recommend anyone who should be against the wildcard Blacklisting would whitelist it them self, as removing it, would also removes the "build warning" to other users, that there is something unwanted happening within this domain.

**Comment by jawz101** [comment]
if it causes user breakage or if it isn't actually used to communicate ads or tracking I would prefer an entry not be there.

The other thing with domain.TLD entries is if it's unnecessary to block it I don't want it if it blocks me from going to their website to learn about the company.

**Comment by spirillen** [comment]
Another thing is, why should 

```
accesstrade.com.vn
fast.accesstrade.com.vn
```

be removed @bigdargon ??

**Comment by spirillen** [comment]
> if it causes user breakage

Wouldn't that be most of the list then :laughing: :rofl: 

> The other thing with domain.TLD entries is if it's unnecessary to block it I don't want it if it blocks me from going to their website to learn about the company.

ad1)
I know :smile: 

ad2)
I uses the Tor-browser to that, it is also a "clean" way to do it, and it is a clean browser without any history. Also if the site is seriously badware, the rest of my system isn't affected :+1: 

**NOTE**: for other users, Tor browser are NOT protecting you against any attacks like worms or viruses, for that you'll need a separated virtual environment on a separated network.

**Comment by jawz101** [comment]
... the other thing is I am personally not familiar with Vietnamese sites & apps and originally added them a long time ago

**Comment by spirillen** [comment]
> ... the other thing is I am personally not familiar with Vietnamese sites & apps

You are not alone in that matter :)

However both of you (@bigdargon & @jawz101) might be interested in this cooperation, https://www.mypdns.org/T3681 and if any of you have anything you can add, please feel free to.

**Comment by bigdargon** [comment]
@jawz101 Thank you!

@spirillen `Accesstrade` is just a deep link in the e-commerce field (also known as affiliate marketing), they do not lead to malicious application. `accesstrade.com.vn` is the backup domain name of `accesstrade.vn`
P/s: The project you mentioned above blocks phishing url addresses, they do not block ads and trackers in Vietnam.

**Comment by spirillen** [comment]
> @bigdargon worte..
> 
> @spirillen `Accesstrade` is just a deep link in the e-commerce field (also known as affiliate marketing), they do not lead to malicious application.

They are not blocked at my end for that, they are marked , AdWare, TrackWare and Redirecting (highly probably with tracking involved)

> they do not lead to malicious application

:laughing: I consider all marketing material as malicious, they never tell the truth :grin: 

> `accesstrade.com.vn` is the backup domain name of `accesstrade.vn`

Super, I was wondering about this, but had the idea about that

> P/s: The project you mentioned above blocks phishing url addresses, they do not block ads and trackers in Vietnam.

Thanks, as I wrote in <https://www.mypdns.org/Z3#1052> it have been some troublesome to visit his site, hence the project it self.

PS: Is it possible you can fill in any answers, that @7onez haven't replied to? or just in general enlighten us all about `chongluadao.vn` project?.

**Comment by bigdargon** [comment]
> :laughing: I consider all marketing material as malicious, they never tell the truth :grin:

@spirillen Maybe! I choose not to block for a better experience. In particular, my project is linked to Adguard DNS. Therefore, if the block is too strong, the user will not like it.
P/s: How can I personally communicate with you about the `chongluadao.vn` project? There are issues I cannot share publicly.

**Comment by spirillen** [comment]
> P/s: How can I personally communicate with you about the `chongluadao.vn` project?

Keybase (spirillen) or <https://www.mypdns.org/conpherence/> Set the rules for who can participate/view

![image](https://user-images.githubusercontent.com/44526987/112208839-19cf0200-8c19-11eb-8cbb-9fc9c9b515c4.png)
