### ISSUE TITLE
Remove app.hubspot.com from hosts.txt

### ISSUE THREAD

**Issue by beaurepair** [AdAway/adaway.github.io#222]
This domain points to the HubSpot CRM and does not serve ads.
Looks like it was added in https://github.com/AdAway/adaway.github.io/commit/18ba751904548da1dc0ee998bfcd04754ae0789d

**Comment by acerbisgianluca** [comment]
Furthermore email trackers are hosted on other subdomains which were already blocked.

**Comment by beaurepair** [comment]
Fixed in https://github.com/AdAway/adaway.github.io/commit/795ad3da39b6be6a406538b62b8759ad91832e54

Thanks @jawz101

**Comment by jawz101** [comment]
Thanks.  Sorry about that.  I could've sworn I fixed it when you put in this issue but I guess I closed the tab too soon.
