### ISSUE TITLE
fast.wistia.com blocked, renders Wistia video player blank

### ISSUE THREAD

**Issue by akarle** [AdAway/adaway.github.io#224]
Hi all,

First, thanks for your efforts! I've been using your ad-list indirectly through the pi-hole for quite some time!

I wanted to flag that fast.wistia.com was added in this commit 18ba751904548da1dc0ee998bfcd04754ae0789d, which rendered the Wistia video player ([served via that URL](https://wistia.com/support/developers/e-v1)) blank.

We're using the video player to serve course content at https://monthly.com, and it's left a couple users (myself included) confused.

Would you consider removing fast.wistia.com from the blacklist? If not, any information you could give as to why it's blocked would be great so that I can communicate it to the Wistia team!

Thanks for your time, help, and consideration!

Alex

**Comment by jawz101** [comment]
removed.  thanks

**Comment by akarle** [comment]
thanks for the fast response! I appreciate it!
