### ISSUE TITLE
Please remove split.io domains from the default block list

### ISSUE THREAD

**Issue by dogeared** [AdAway/adaway.github.io#227]
events.split.io, cdn.split.io, and sdk.split.io are used for Split.io's customer signup and developer services. Neither are directly related to serving ads.

**Comment by RmACK123** [comment]
Clickup is now broken for me due to its use of split.io.
Thanks for the explanations in this thread about why split.io is blocked.

Heads-up to fellow Clickup users who may wish to whitelist split.io in their blockers.
