### ISSUE TITLE
Block midasplayer.com break king.com

### ISSUE THREAD

**Issue by bigdargon** [AdAway/adaway.github.io#228]
Delete domain names

```
midasplayer.com
k1.midasplayer.com
k1qa.midasplayer.com
```

Since NextDNS blocks the subdomains, I suggest deleting the domain `midasplayer.com`

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +55 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/diamonddiaries/logos/gameLogo.png?_v=1qe8ods` |
| +55 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/diamonddiaries/logos/gameLogo.png?_v=1qe8ods` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/jobs/jobsPromotion/bubbleMint.webp?_v=1y5jo3k` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/gameCharacters/firefly-facingRight.webp?_v=1u828jl` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/branding/featured-shape-mask-big-2_top.svg?_v=18n4dm3` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/jobs/jobsPromotion/bg_jobs.webp?_v=gxmd9e` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/gameCharacters/betty.webp?_v=fft2p5` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/featuredNews/diamonddiaries.webp?_v=fysplh` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/gamePromotion/AllGamesGroup.webp?_v=zzmauw` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/candycrush/logos/gameLogo.webp?_v=15co5f6` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/gamePromotion/yeti_tiffi_party.webp?_v=6abx0s` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/favicons/favicon-16x16.png?_v=18aenx6` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/favicons/apple-touch-icon.png?_v=1qrz32z` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/diamonddiaries/logos/gameLogo.webp?_v=pcxx9u` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/diamonddiaries/logos/gameLogo.png?_v=1qe8ods` |
| +54 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/crashontherun/logos/gameLogo.webp?_v=18jl1hc` |
| +53 |  |  | `www.king.com` | 3 | font | `https://k1.midasplayer.com/images/fonts/king-icon.ttf?_v=v5f1ad` |
| +53 |  |  | `www.king.com` | 3 | font | `https://k1.midasplayer.com/images/fonts/SuperGroteskWebPro-Medium.woff?_v=1ikapgh` |
| +53 |  |  | `www.king.com` | 3 | font | `https://k1.midasplayer.com/images/fonts/SuperGroteskWebPro.woff?_v=135js77` |
| +53 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/gameCharacters/panda.webp?_v=tjfzma` |
| +53 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/icons/previous_icon.svg?_v=1hi5yoa` |
| +53 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/icons/next_icon.svg?_v=1nstxcn` |
| +53 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/pyramid/appIcon.webp?_v=7f0z2f` |
| +53 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/petrescue/appIcon.webp?_v=u9h6jn` |
| +53 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/diamonddiaries/appIcon.webp?_v=1041rzc` |
| +53 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/candycrushfriends/appIcon.webp?_v=laashb` |
| +53 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/candycrushjelly/appIcon.webp?_v=1yt4y1x` |
| +53 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/alphabetty/appIcon.webp?_v=1hxnofn` |
| +53 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/bubblewitch3/appIcon.webp?_v=12s4hhq` |
| +53 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/knighthood/appIcon.webp?_v=13u7ksy` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/crashontherun/appIcon.webp?_v=womzp1` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/blossomblast/appIcon.webp?_v=o4jfc8` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/papapear/appIcon.webp?_v=2z6pvo` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/diamonddigger/appIcon.webp?_v=1z00prs` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/farmheroes/appIcon.webp?_v=khx44f` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/bubblewitch2/appIcon.webp?_v=xmjbpp` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/candycrushsoda/appIcon.webp?_v=1gfkp5m` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/farmheroessupersaga/appIcon.webp?_v=72k2wo` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/candycrush/appIcon.webp?_v=1oik1o0` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/icons/socialLinks-instagram.svg?_v=1xf3d6g` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/icons/socialLinks-linkedIn.svg?_v=klgvxs` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/icons/socialLinks-youtube.svg?_v=ght55w` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/icons/socialLinks-tumblr.svg?_v=sjmdqf` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/icons/socialLinks-twitter.svg?_v=otki6` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/icons/socialLinks-facebook.svg?_v=17wunk` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/branding/footer-shape-bg.svg?_v=1ovufyw` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/featuredNews/playBtn.png?_v=qk3cfa` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/campaigns/crashontherun/PreReg_home.webp?_v=u5zmuj` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/featuredNews/crashCampaign.webp?_v=naev91` |
| +52 |  |  | `www.king.com` | 3 | script | `https://k1.midasplayer.com/js/41.478da3c17abc8ed847de.chunk.js` |
| +52 |  |  | `www.king.com` | 3 | css | `https://k1.midasplayer.com/css/41.478da3c17abc8ed847de.min.css` |
| +52 |  |  | `www.king.com` | 3 | script | `https://k1.midasplayer.com/js/40.46f6ad59de838b6e5d79.chunk.js` |
| +52 |  |  | `www.king.com` | 3 | css | `https://k1.midasplayer.com/css/40.46f6ad59de838b6e5d79.min.css` |
| +52 |  |  | `www.king.com` | 3 | script | `https://k1.midasplayer.com/js/39.bcaaa5632695d20192ed.chunk.js` |
| +52 |  |  | `www.king.com` | 3 | script | `https://k1.midasplayer.com/js/42.e7d9f08c9dc92c38f5f6.chunk.js` |
| +52 |  |  | `www.king.com` | 3 | css | `https://k1.midasplayer.com/css/42.e7d9f08c9dc92c38f5f6.min.css` |
| +52 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/games/crashontherun/logos/gameLogo.png?_v=tap5en` |
| +51 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/logos/kingLogoRebrand.svg?_v=ova6zp` |
| +51 |  |  | `www.king.com` | 3 | script | `https://k1.midasplayer.com/js/app.min.js?_v=1n8q80d` |
| +51 |  |  | `www.king.com` | 3 | css | `https://k1.midasplayer.com/css/app.min.css?_v=fvr69j` |
| +47 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/favicons/favicon-16x16.png?_v=18aenx6` |
| +47 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/favicons/apple-touch-icon.png?_v=1qrz32z` |
| +47 |  |  | `www.king.com` | 3 | script | `https://k1.midasplayer.com/js/app.min.js?_v=1n8q80d` |
| +47 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/logos/kingLogoRebrand.svg?_v=ova6zp` |
| +47 |  |  | `www.king.com` | 3 | script | `https://k1.midasplayer.com/js/app.min.js?_v=1n8q80d` |
| +47 |  |  | `www.king.com` | 3 | css | `https://k1.midasplayer.com/css/app.min.css?_v=fvr69j` |
| +2 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/favicons/favicon-16x16.png?_v=18aenx6` |
| +2 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/favicons/apple-touch-icon.png?_v=1qrz32z` |
| +2 |  |  | `www.king.com` | 3 | script | `https://k1.midasplayer.com/js/app.min.js?_v=1n8q80d` |
| +2 |  |  | `www.king.com` | 3 | image | `https://k1.midasplayer.com/images/logos/kingLogoRebrand.svg?_v=ova6zp` |
| +2 |  |  | `www.king.com` | 3 | script | `https://k1.midasplayer.com/js/app.min.js?_v=1n8q80d` |
| +2 |  |  | `www.king.com` | 3 | css | `https://k1.midasplayer.com/css/app.min.css?_v=fvr69j` |
</details>

**Comment by jawz101** [comment]
removed most of them.  Fyi, NextDNS' default list is based on StevenBlack which uses Adaway as one of its sources- so me removing something will eventually remove it from NextDNS' standard list.

https://github.com/nextdns/metadata/blob/master/privacy/blocklists/nextdns-recommended.json

**Comment by bigdargon** [comment]
@jawz101 Yes i understand that! Thanks for considering removing!

**Comment by bigdargon** [comment]
@jawz101 As for the `k1.midasplayer.com` domain name you have not removed. If I visit the `king.com` site, this domain contains the script and font of the website. Can you test it?

**Comment by jawz101** [comment]
I had removed it shortly after

**Comment by bigdargon** [comment]
Sorry @jawz101 I just check commit in this issues! :laughing:
