### ISSUE TITLE
Change onesignal.com to cdn.onesignal.com

### ISSUE THREAD

**Issue by bigdargon** [AdAway/adaway.github.io#229]
Some mobile apps use Onesignal services to send in-app notifications. Unfortunately, when the domain `api.onesignal.com` is blocked the application crashes.

With the domain `onesignal.com` blocked, using NextDNS will block subdomains including` api.onesignal.com`. Therefore, I suggest changing the domain name `onesignal.com` to` cdn.onesignal.com` to block tracking at sites with push notifications.

Thanks!

**Comment by jawz101** [comment]
removed onesignal.  I probably won't add cdn.onesiignal.com since it isn't found in Android apk traffic per VirusTotal.com analysis
