### ISSUE TITLE
m-motu.doglobal.net break store Photo Wonder app

### ISSUE THREAD

**Issue by bigdargon** [AdAway/adaway.github.io#234]
Domain `m-motu.doglobal.net` blocked, cannot open store on Photo Wonder app. Please check this. Thanks!

Edit: I captured some url in ios app 

![4E9306CA-8FE2-4F22-8592-EF265655CE9A](https://user-images.githubusercontent.com/10969626/113382724-71edcd00-93ac-11eb-899f-e6d00c06b437.png)

**Comment by jawz101** [comment]
removed.  thanks
