### ISSUE TITLE
sdk.privacy-center.org

### ISSUE THREAD

**Issue by gita6t5** [AdAway/adaway.github.io#236]
Blocks video playback
https://koscierzyna.naszemiasto.pl/waldemar-b-byly-senator-oskarzony-o-znecanie-sie-nad-psem/ar/c1-8213337
![Zrzut ekranu z 2021-04-07 19-33-51](https://user-images.githubusercontent.com/80338577/113909651-356d0780-97d8-11eb-860a-b1452a894c97.png)

**Comment by jawz101** [comment]
removed.  thanks
