### ISSUE TITLE
Remove *.sailthru.com domains

### ISSUE THREAD

**Issue by georgekliao** [AdAway/adaway.github.io#238]
Hi,

Can you please remove the *.sailthru.com domains -- particularly cb.sailthru.com and link.sailthru.com domains? Certain email links will not function properly with cb.sailthru.com and link.sailthru.com domains blocked.

Thanks,
George

**Comment by jawz101** [comment]
I removed most of them based on VirusTotal checks to see what communicating files each may have had  https://www.virustotal.com/gui/domain/api.sailthru.com/relations
