### ISSUE TITLE
Overblock breaks TheRegister.co.uk

### ISSUE THREAD

**Issue by bentasker** [AdAway/adaway.github.io#239]
Commit [c2a72b3](https://github.com/AdAway/adaway.github.io/commit/c2a72b3c7918aa277af00bf5b18e2c079c13f2d6) blocks `regmedia.co.uk`

[The Register](https://www.theregister.com) use that domain to serve article thumbnails etc.

Their ads JS is actually served by the top level domain, so there's no real gain in this block

**Comment by jawz101** [comment]
removed.  thanks
