### ISSUE TITLE
Blacklisting of midrollmedia.mc.tritondigital.com breaks some podcast streaming

### ISSUE THREAD

**Issue by RooneyMcNibNug** [AdAway/adaway.github.io#240]
Hello there,

Thank you for creating this useful list.

I would like to request removal of the following subdomain: `midrollmedia.mc.tritondigital.com`

I had to whitelist this in order to get some podcasts to play on popular audio streaming services, as they are making `GET` requests to the .mp3s for the episodes hosted on this domain.

Regards,
JA

**Comment by jawz101** [comment]
removed.  thanks!
