### ISSUE TITLE
Blocking chtbl.com breaks podcast streaming

### ISSUE THREAD

**Issue by natanlao** [AdAway/adaway.github.io#243]
c2a72b3 blocks chtbl.com, which prevents downloading or streaming podcasts on some iOS apps, including Spotify, Pocket Casts, and Overcast. It appears sufficient to allow-list chtbl.com (and leave blocks on ext.chtbl.com and web.chtbl.com intact).

I'm happy to open this PR myself, but just wanted to check list policy -- sorry if it's documented somewhere, and I missed it. chtbl.com is linked to Chartable, a podcast analytics service. Is it acceptable to omit rules for known tracking services to keep apps working without intervention, or would it be better for me to leave the list as-is and document this on [this wiki page](https://github.com/AdAway/AdAway/wiki/ProblematicApps)?

**Comment by spirillen** [comment]
Well this repo doesn't have a `CONTRIBUTING.md` :smirk: so you can't find it.

But make the changes to the https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt in a fork and do the merge request (PR) a long side a good comment describing why your suggest the changes. 

As always logs are good evidence and history record  to keep for later.

**Comment by natanlao** [comment]
Great! PR incoming.

**Comment by kousu** [comment]
I was just about to come report the same thing!

Thanks for jumping on it both of you.

Do we know what motivated adding it in the first place? I guess Chartable makes money off analytics?
