### ISSUE TITLE
potential additions

### ISSUE THREAD

**Issue by jawz101** [AdAway/adaway.github.io#25]
```
launches.appsflyer.com
inapps.appsflyer.com
cdp.cloud.unity3d.com
config.uca.cloud.unity3d.com
www.geoplugin.net
metric-android-am.road404.com
outcome-ssp.supersonicads.com
www.leanplum.com
www.google-analytics.com
freegeoip.com
ads.sessiongames.com
1cef.playfabapi.com
cx.atdmt.com
api.leanplum.com
app.adjust.com
stats.unity3d.com
ssl.google-analytics.com
reports.crashlytics.com
```

update: this one merged

**Comment by AnXh3L0** [comment]
I agree with all of these as they're the typical most used trackers nowadays.

**Comment by spirillen** [comment]
Just as side note

```regex
(*\.|^)google(-)?analytics.com
```
Isn't that only interesting if a user only use óne list? I would suppose users are using several lists.

Alternatively I would suggest something like these in addition to OP's suggestion

http://wiki.mypdns.org/changeset/9ccd1afd3606a8a249e9d14e05c88142d25b1c18/Matrix#file1

<details><summary>or in host style format:</summary>

```python
sublytics-5df2e9a153dc8.com
track.sublytics-5b89aa9c7351b.com
track.sublytics-5b8be9c3dfba1.com
track.sublytics-5bb3bd7244788.com
track.sublytics-5bbdf9e493019.com
track.sublytics-5bbe366b366e7.com
track.sublytics-5be5e6127db50.com
track.sublytics-5be5edecc10bf.com
track.sublytics-5c12ac105f653.com
track.sublytics-5c180532b110b.com
track.sublytics-5c4b49e17bf18.com
track.sublytics-5c50b8bed88f6.com
track.sublytics-5c5dc83ea3197.com
track.sublytics-5c671946c725e.com
track.sublytics-5c75a3373a4d0.com
track.sublytics-5ca396601f872.com
track.sublytics-5caf966ded053.com
track.sublytics-5cb8c2016ba8d.com
track.sublytics-5ce6f319781d8.com
track.sublytics-5cf6bedde8718.com
track.sublytics-5cf6beeda63eb.com
track.sublytics-5cf6befdf0877.com
track.sublytics-5cf6bf1b2d888.com
track.sublytics-5cf7e7735ee3f.com
track.sublytics-5cfde4b825959.com
track.sublytics-5cffe909e69e6.com
track.sublytics-5cffef1b200fc.com
track.sublytics-5d028ee628e1e.com
track.sublytics-5d02a489ae8b0.com
track.sublytics-5d0bcdd852673.com
track.sublytics-5d0bf30bbda96.com
track.sublytics-5d0d27a0b2c28.com
track.sublytics-5d0d27b33a934.com
track.sublytics-5d0d280c57ef0.com
track.sublytics-5d24d6515d46a.com
track.sublytics-5d27647017cfe.com
track.sublytics-5d49cbe5e8d5c.com
track.sublytics-5d49d796f001d.com
track.sublytics-5d6fc61ecbaab.com
track.sublytics-5d6fcf0a813fd.com
track.sublytics-5d702336c312b.com
track.sublytics-5d717a9849fd6.com
track.sublytics-5d717aa6c98a9.com
track.sublytics-5d83d314147f7.com
track.sublytics-5d94cd99d28f3.com
track.sublytics-5da0c4b264e9b.com
track.sublytics-5da0c4c270013.com
track.sublytics-5dae180ba29aa.com
track.sublytics-5daf51a90c4c7.com
track.sublytics-5daf51df0ce6a.com
track.sublytics-5dafc41cd91a6.com
track.sublytics-5db087d02a8b8.com
track.sublytics-5db09a3d41b33.com
track.sublytics-5db9e5dd1b2c2.com
track.sublytics-5db9fa0b5700f.com
track.sublytics-5dc441b214383.com
track.sublytics-5dc441f31b1c6.com
track.sublytics-5dc9aab632da9.com
track.sublytics-5df8eec4bca66.com
track.sublytics-5e0e3b928b4bd.com
```

<details>

**Comment by jawz101** [comment]
I'm just using this list one in Blokada or whichever Android adblocker and have my browsers excluded.  Since Firefox for Android has uBlock Origin for web-based ads, I'm trying to isolate traffic from apps and seeing what the most popular mobile analytic libraries cause.  Ideally, this list would be just for app ad/tracking domains and leave other lists to cover malware, and web browsing domains.

**Comment by spirillen** [comment]
I know, that's why i added the additional suggestions :tongue: those are initially from my own DNSdist :+1:

**Comment by PerfectSlayer** [comment]
You can add all the tracker you want as soon as you don't face a sh**storm of broken app or site from users 😛 

I don't know if it can help you but the recent Firefox blocking feature is based of disconnect list which is available here: https://github.com/disconnectme/disconnect-tracking-protection

**Comment by jawz101** [comment]
Well, my goal is to make a list not based on other lists and be strictly DNS entries that come from mobile apps- that is not those only found when browsing web pages or from, say, spyware programs installed on a Windows computer.

Lists get too clunky when they merge each other's and I'm trying to stick back to that original thought.  When I started mine it was maybe a few hundred.  Then I added Exodus Privacy's domains from their app analysis scans, AdGuard's mobile list, and a few other iOS and Android lists by others that shared similar mobile-only entries.  I even enumerated subdomains with VirusTotal and some subdomain scraper sites for some companies if they followed that 3745.doubleclick.net pattern.  I also tried to find lists that represented some regional-specific mobile ad companies since I may not ever download a Vietnamese game, for example.

All of that just ended up being a huge turd.  I like how the Adaway list was just a few hundred mobile-only domains.  It was unique and purpose-driven but I knew it had become stale.  My list still carries some of that baggage from old merges so I want to chip away at that to get it down to your Tapjoy, Vungle, Supersonic ads, Adjust, Segment type entries because those are the mobile ad and tracking companies.

I use NetGuard with my browser whitelisted (and running its own adblocker), and just see what my other apps do.  I'll also look at the app with Dexplorer and check VirusTotal to see if it has ties to Android ad and analytic sdk's, look for maven repositories and company project pages on GitHub, or their developer documentation on their site.  Doing this process I've added maybe 50 tracker signatures to the Exodus Privacy Project as well.

It's just a hobby I made for myself because it blocks the majority of useless data use from apps, reduces distractions, and the idea that we walk around recording everything we do, and companies leverage that behavior pattern while playing Pokemon without me fully understanding the implication bugs me.

**Comment by PerfectSlayer** [comment]
Don't worry, I didn't post the disconnect list to merge it to the AdAway one.
It was more to help you to identify if hosts are tracking ones or not.

It's really nice of you to improve the Exodus project. I wish I could work more with them (the adware feature from AdAway should be replace by their scan feature for example).
I know they are french (like me) so it should be easier to work with but I never found the time to.

I am also concerned about privacy, that's why I maintain this app on my free time. The adblocker feature is more to attract users but for me, the real app interest is the privacy improvement it offers. I am a developer myself so I understand the need to display ads to pay the bills. But selling user profiles and tracking them is a no-go for me (the best to me is paid app or in app payment but I don't think users enjoy them…).

**Comment by spirillen** [comment]
> the best to me is paid app or in app payment but I don't think users enjoy them…

If that would actually leads to non Tracking/Ads it would be a deal I would get into. Cos like both of you, privacy matters to me. Which leads to the idea of, what you do online is a business between you and the one you connects to, no one else.... like in `chmod -R 2000 nobody `

`2000` is the sticky bits :imp:

**Comment by jawz101** [comment]
```
js-agent.newrelic.com
ip-api.com
onesignal.com
c.evidon.com
app.adjust.com
ratrodserver.com
c.betrad.com
freegeoip.net
m.quantserve.com
pixel.quantserve.com
sync.republer.com
p.skimresources.com
t.skimresources.com
r.skimresources.com
t.trafmag.com
rumcdn.geoedge.be
sync.adtelligent.com
events.browsiprod.com
sync.search.spotxchange.com
```

**Comment by vladc** [comment]
> ip-api.com
ip-api.com is a Geolocation API, it does not does not collect, store, or share data regarding its users or API requests. It's a simple API for returning approximate location of an IP address.

**Comment by jawz101** [comment]
I understand.  I've removed it on my MATS list in the past for the same reason.  The only reason I reconsidered it is because AdGuard blocks it as well and their site doesn't give any indication of ownership.
