### ISSUE TITLE
False positive for px-conf.perimeterx.net and client.perimeterx.net

### ISSUE THREAD

**Issue by omriiluz** [AdAway/adaway.github.io#251]
Hello,
A few of the domains used by PerimeterX are flagged for blocking in your list, for example px-conf.perimeterx.net and client.perimeterx.net but also others. These domains are used by PerimeterX, a cyber security and anti-fraud company, to protect thousands of sites and applications from various cyber attacks. PerimeterX has nothing to do with advertisement, we do not display, target, sell, buy or do anything that is even remotely related to ads. 

PerimeterX is fully compliant with privacy regulations all over the world (GDPR, CCPA, etc. ). We do not sell user information or use it in any way other than to decide if if the user is a threat to the site.

By not being able to access these domains certain apps and sites, your users (and ours) will have negative experience and might not be able to use sites and apps as a result.

Would highly appreciate if you can remove these domains from the list.

**Comment by omriiluz** [comment]
Thanks for adding the reference. I've been tracking this upstream from NextDNS to StevenBlack to adaway.

**Comment by jawz101** [comment]
removed.  Looking over your website, you are doing the Lord's work.   I despise cyber fraud and don't want to affect your product

**Comment by Maxcodesthings** [comment]
This was not removed an still exists in master branch. I have a record amount of hits on this domain. Why is this still blocked?
https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt#L7975

**Comment by jawz101** [comment]
removed.  It must've been readded by mistake at some point.  Sorry about that.
