### ISSUE TITLE
Blocking stats.pingdom.com blocks all pingdom public status pages

### ISSUE THREAD

**Issue by Bertware** [AdAway/adaway.github.io#252]
Blocking stats.pingdom.com completely blocks public status pages, which are not used for tracking or gathering statistics, but to communicate downtime and server issues. 

Example broken sites: http://status.trafiklab.se/, http://status.inera.se/, http://status.svd.se/ . This system is used worldwide, the examples just happen to be Swedish.

A google search for pingdom status pages (all broken due to CNAME to stats.pingdom.com): https://www.google.com/search?q=pingdom+public+reports

**Comment by jawz101** [comment]
removed.  thanks
