### ISSUE TITLE
gsdk.proximabeta.com

### ISSUE THREAD

**Issue by bigdargon** [AdAway/adaway.github.io#256]
I have been playing a game (https://apps.apple.com/vn/app/garena-li%C3%AAn-qu%C3%A2n-mobile/id1150288115 ) and found out that this domain has been blocked. When resolving https I get this url https://cloud2.gsdk.proximabeta.com:18082/?cmdid=3&appid=i1105779914

So what do you think about why this domain is blocked?

If this is a mistake, can you delete this domain and subdomain? Thank you!

![54038C6F-A174-407A-BA29-DA4CFE92DBD7](https://user-images.githubusercontent.com/10969626/120883001-01119e00-c605-11eb-8ec7-e0220a087ee9.png)

**Comment by jawz101** [comment]
removed .  thanks
