### ISSUE TITLE
[false-positive ???] glimmer.hearstapps.com

### ISSUE THREAD

**Issue by dnmTX** [AdAway/adaway.github.io#257]
@jawz101  as seen here: https://www.menshealth.com/entertainment/a36651546/in-the-heights-first-8-minutes-trailer/
it fails to open the mini player,which provides content from the same website,and didn't look like pushing ads or whatever.
I'm pretty sure you had a good reason to block it so inspect when you can. Thanks 👍 
![miniPlayer](https://user-images.githubusercontent.com/34774426/121486139-7d560980-c996-11eb-9816-39ab68242ea5.PNG)

**Comment by jawz101** [comment]
I'll remove it in a little bit.  Driving home.  But there's not always a good reason why some things were blocked.  Something with an odd name, such as calling something "glimmer," stands out.  Sometimes things not following their standard naming schemes are the crap.

**Comment by dnmTX** [comment]
Thanks @jawz101 👍
