### ISSUE TITLE
Some domains in Tiktok app

### ISSUE THREAD

**Issue by bigdargon** [AdAway/adaway.github.io#259]
There are some blocked domains in tiktok app, which in my opinion are not ads or trackers.

`i.isnssdk.com` This domain is redirected to this page http://i.isnssdk.com/wap/privacy_policy

`log.byteoversea.com.edgekey.net` This domain name is the CNAME of the domain name `log.byteoversea.com` If you block this domain name in some countries (in Vietnam), comments will not be displayed in the video.

In my opinion, the Tiktok application collects personal data for the purpose of personalizing videos to approach trends. Ideally, without using the application, Tiktok will not collect much data. And should only be blocked, when the site inserts a 3rd party tracking domain like `analytics.tiktok.com` `analytics-sg.tiktok.com` `ads.tiktok.com` `ads-sg.tiktok.com`

**Comment by jawz101** [comment]
I will remove what is causing an application not to function as the user expects.

If blocking a domain does not cause a perceived loss of functionality to the user, I would rather play it safe and keep it blocked.

Which ones specifically are causing problems for you?

**Comment by bigdargon** [comment]
I want to remove 2 domains

```
i.isnssdk.com
log.byteoversea.com.edgekey.net
```

Because blocking it will make the app not work well. Thank you!

**Comment by jawz101** [comment]
fixed.thanks
