### ISSUE TITLE
FP: pusher.com

### ISSUE THREAD

**Issue by spirillen** [AdAway/adaway.github.io#26]
`pusher.com` is used by `travis-ci.(com|net)` to call logs and current status

Only `stats.pusher.com` should be blocked for statistic tracking of users.

![image](https://user-images.githubusercontent.com/44526987/72405189-473c3800-3758-11ea-9765-bc59816f9952.png)

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +53 |  |  | travis-ci.com | 3 | xhr | `https://sock126-mt1.pusher.com/pusher/app/59236bc0716a551eab40/84/1bp7c4n6/xhr_send?t=1579062757722&n=20` |
| +53 |  |  | travis-ci.com | 3 | xhr | `https://sock126-mt1.pusher.com/pusher/app/59236bc0716a551eab40/84/1bp7c4n6/xhr_send?t=1579062757722&n=20` |
| +28 |  |  | travis-ci.com | 3 | xhr | `https://sock126-mt1.pusher.com/pusher/app/59236bc0716a551eab40/84/1bp7c4n6/xhr_send?t=1579062732855&n=19` |
| +28 |  |  | travis-ci.com | 3 | xhr | `https://sock126-mt1.pusher.com/pusher/app/59236bc0716a551eab40/84/1bp7c4n6/xhr_send?t=1579062732855&n=19` |
| +28 |  |  | travis-ci.com | 3 | xhr | `https://sock126-mt1.pusher.com/pusher/app/59236bc0716a551eab40/84/1bp7c4n6/xhr_send?t=1579062732850&n=18` |
| +28 |  |  | travis-ci.com | 3 | xhr | `https://sock126-mt1.pusher.com/pusher/app/59236bc0716a551eab40/84/1bp7c4n6/xhr_send?t=1579062732850&n=18` |
| +28 |  |  | travis-ci.com | 3 | xhr | `https://sock126-mt1.pusher.com/pusher/app/59236bc0716a551eab40/84/1bp7c4n6/xhr_send?t=1579062732685&n=17` |
| +28 |  |  | travis-ci.com | 3 | xhr | `https://sock126-mt1.pusher.com/pusher/app/59236bc0716a551eab40/84/1bp7c4n6/xhr_send?t=1579062732685&n=17` |
| +26 |  |  | travis-ci.com | 3 | xhr | `https://sockjs.pusher.com/pusher/app/59236bc0716a551eab40/84/1bp7c4n6/xhr_streaming?protocol=7&client=js&version=5.0.2&t=1579062730862&n=16` |
| +26 |  |  | travis-ci.com | 3 | xhr | `https://sockjs.pusher.com/pusher/app/59236bc0716a551eab40/84/1bp7c4n6/xhr_streaming?protocol=7&client=js&version=5.0.2&t=1579062730862&n=16` |
| +0 |  |  | travis-ci.com | 3 | xhr | `https://sock126-mt1.pusher.com/pusher/app/59236bc0716a551eab40/314/cbt3ga1j/xhr_send?t=1579062704900&n=15` |
| +0 |  |  | travis-ci.com | 3 | xhr | `https://sock126-mt1.pusher.com/pusher/app/59236bc0716a551eab40/314/cbt3ga1j/xhr_send?t=1579062704900&n=15` |
</details>

original posted here https://github.com/jawz101/MobileAdTrackers/issues/30

**Comment by jawz101** [comment]
thanks.  removing

**Comment by spirillen** [comment]
Ok, now I believe I'm done updating all my scripts :unamused: after you moved the git, But what the heck... now it gets updated :100:

**Comment by jawz101** [comment]
I do not understand

**Comment by spirillen** [comment]
https://github.com/funilrys/PyFunceble/issues/74#issuecomment-574317566
