### ISSUE TITLE
Write time stamp inside the host file

### ISSUE THREAD

**Issue by zputnyq** [AdAway/adaway.github.io#260]
Hi there,
So far, it's so good using this host.
I think it's better if time stamp of update is written inside the host file like in most hosts so it could ease people who don't use adaway when they directly open raw link.

**Comment by spirillen** [comment]
I would second your suggestion, but until that might be happenig you can use the committed time

![image](https://user-images.githubusercontent.com/44526987/122971868-d0b15a00-d38f-11eb-892e-4dd4c76faa39.png)
