### ISSUE TITLE
onelink.me

### ISSUE THREAD

**Issue by bigdargon** [AdAway/adaway.github.io#263]
When using nextdns, I won't be able to select "download the app"

Website: https://baemin.vn/

Link: https://baemin.onelink.me/jjXg/landing

Request removal domain  `onelink.me`

Thanks!

**Comment by spirillen** [comment]
@bigdargon :confused: 

Should we delete [appsflyer.com](https://mypdns.org/my-privacy-dns/matrix/-/issues/2067) googleanalytics at the same time?

Personally I would call this a stay with information's about how bad this domain is, and why the exclusive link should be considered broken

**Comment by bigdargon** [comment]
@spirillen 

> Should we delete appsflyer.com googleanalytics at the same time?

Depending on the purpose and influence of the domain name, I decide to block or not? For example, the domain `google-analytics.com` used to track, statistics of the website, blocking it does not cause the website to break. So we can block it completely, including subdomains.

But, with the `appsflyer.com` domain, when we block this domain completely, some game or application homepages will not be able to click the direct link to switch to the app store (example https://lienquan.garena.vn with link https://app.appsflyer.com/com.garena.game.kgvn?pid=OrganicA&c=obt_lp_and https://app.appsflyer.com/id1150288115?pid=OragnicA&c=cbt_lp_ios) So some whitelists like Adguard DNS, they will ignore this domain so as not to affect the user experience (`@@||app.appsflyer.com^|` in https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt).

`onelink.me` is a shortening service that helps developers track application installations. In addition, it helps the user to be directed to the clicked object (when we have installed the application). It is true that it is "tracking", but for good purposes, it is not intended to "collect" and "sell" user data.

> Personally I would call this a stay with information's about how bad this domain is, and why the exclusive link should be considered broken

In my opinion, blocking trackers with a browser filter or filtering with the Adguard for Android app (using filters) will reduce tracking more. With blocking domains by DNS sometimes reduces the user experience.

**Comment by spirillen** [comment]
Hey @bigdargon sorry you didn't catch the irony in my last message....

I'm getting a bit confused here... 

> In my opinion, blocking trackers with a browser filter or filtering with the Adguard for Android app (using filters) will reduce tracking more. With blocking domains by DNS sometimes reduces the user experience

What is it you believes is the different here?

DNS is using caching = ram, hosts files uses tarring and expensive Disk I/O ?

Non the less, I'll still prefer a blacklist actually do lists "`bad`" object AND then the individual user determines by them self, what should be allow to "`slip`" through based on knowledge. Relaying on other to determining on my behalf, which first or third party is to be allowed to collect data about me or any devices on my network.
This is also the idea behind my project, ass you have the [rpz-passthru.](https://mypdns.org/mypdns/support/-/wikis/RPZ-record-types#the-passthru-action-cname-rpz-passthru) in the RPZ, or as alternative and end-user can use the dnsdist and bypass specified domains from there default rules while relaying on remote controlled DNS servers

**Comment by bigdargon** [comment]
@spirillen Sorry, my English is bad so I may not fully understand what you mean. I created this issue here for the reason:

1. Adaway is the upstream of the Steven Black blacklist. And the Steven Black List is the default list of many services like Pihole, Nextdns..
2. Blocking the domain `onelink.me` will also block their homepage
3. This issue created will help @jawz101 track the issue and decide whether to remove or keep it?

**Comment by jawz101** [comment]
Hmm.  [This link](https://www.appsflyer.com/resources/technical-guide-to-attribution-and-deep-linking/setting-the-stage-attribution-deep-linking/) is what I'm reading about what it's used for.  Personally, I don't like to be encouraged to buy things with any techniques.

That's the thing.

Marketing today tries to know who you are, know how much money you have, show you something to buy whether you first wanted it or not, and convince you to buy that thing.

It's either your money or their money and in the wild world of sales, they basically teach salesman that the shopper is just holding onto the salesman's money until they can take it from them.

That's just my outlook and I'm fine with seeing a broken link if it means I don't get convinced to buy something I wasn't looking for until I stumbled across a shiny, targeted, ad for it.

**Comment by spirillen** [comment]
They way you can put these thought in text always astonish me and a "proud dad" :smiley: :older_man: :santa:

**Comment by jawz101** [comment]
Well, my father was a car salesman and when he talked about selling cars his whole demeanor changed.  Everything in sales in a manipulation. [great movie called Suckers](https://www.youtube.com/watch?v=PwBTMw_9fcw)

**Comment by spirillen** [comment]
So true, but I like to the the used car sales man that would we able to sell the over plastered(cosmetic aka plastic padding) Ariana Grande...  :rofl: he would have a set of :ball:'s

youtube = nxdomain :smirk:

**Comment by bigdargon** [comment]
@jawz101 Thanks for your opinion

@spirillen Some of the domains I found in the logs are also for tracking purposes when installing apps

```
page.link
app.link
test-app.link
```

**Comment by spirillen** [comment]
> @jawz101 Thanks for your opinion
> 
> @spirillen Some of the domains I found in the logs are also for tracking purposes when installing apps
> 
> ```
> page.link
> app.link
> test-app.link
> ```

Would you mind adding them to https://mypdns.org/my-privacy-dns/matrix one issue = one domain? then I have them added when I come back home :)

**Comment by bigdargon** [comment]
@spirillen I can't create issue

```
The form contains the following error:

    Your issue has been recognized as spam and has been discarded.
```

![Screenshot 2021-07-12 at 11-46-22 New Issue · My Privacy DNS Matrix](https://user-images.githubusercontent.com/10969626/125232452-d6eb8400-e306-11eb-9882-dd883aa8af3d.png)

**Comment by spirillen** [comment]
Will be fixed asap, it's [Akismet](http://www.akismet.com/) that tricked the blockade :unamused: 

![image](https://user-images.githubusercontent.com/44526987/126134424-d8bfaeca-5c25-4037-af83-c608181f5ad3.png)

![image](https://user-images.githubusercontent.com/44526987/126135320-d18f94bb-09a0-4898-b0f8-807c31871ed1.png)


Could you please try again, I would like to know if I would have to actually disable the Akismet module to have the board working for the purpose it is set up.
