### ISSUE TITLE
o209266.ingest.sentry.io

### ISSUE THREAD

**Issue by Dyf-Tfh** [AdAway/adaway.github.io#266]
Seem like a new alternative to the existing ingest.sentry.io

**Comment by jawz101** [comment]
removing sentry.io altogether.  Looking at their website, it is for crash reports

**Comment by spirillen** [comment]
I would give that a second thought :smirk: 

> this service has popped on countless mobile apps and @itay-grudev does indeed give a fair description of it. Just like every other " error reporting and analysis tool," an "error" can be defined as any event the customer/developer wants it to be. And obviously "analysis" is even more broad. Blocking this service does not degrade the performance of any app's ability to run locally on any device or connect to other external online services in order to perform the task it was marketed to perform, it simply blocks it from connecting to the external online Rollbar services for extraneous "error reporting and analysis" that are completely unrelated to the task which the app was marketed to do and are solely for "internal" purposes, as @itay-grudev stated.

From: https://mypdns.org/my-privacy-dns/matrix/-/issues/1390#relevant-logs-andor-screenshots

Also within the easylist:
  - https://github.com/easylist/easylist/issues/6963
  - https://github.com/easylist/easylist/issues/4060

**Comment by jawz101** [comment]
My stance on some things has evolved over time.  If it's a service strictly designed for crash reports or performance things, I may not block it.  Looking over a lot of the sentry.io website, I'm hard pressed to find anything indicating tracking, monetization, malicious things.  Just error reporting stuff.

**Comment by spirillen** [comment]
That's cool, it's your decision :+1: 
I would just ensure you  didn't make it to hasty :wink:
