### ISSUE TITLE
na61-na62.wagbridge.alibaba.tanx.com

### ISSUE THREAD

**Issue by Franinc** [AdAway/adaway.github.io#268]
Hello, Taobao uses `oms.cainiao.com` to let me check the purchased list.
But the blocked `na61-na62.wagbridge.alibaba.tanx.com` is the CNAME of `oms.cainiao.com`

```
;; QUESTION SECTION:
;oms.cainiao.com.		IN	A

;; ANSWER SECTION:
oms.cainiao.com.	120	IN	CNAME	na61-na62.wagbridge.alibaba.tanx.com.
na61-na62.wagbridge.alibaba.tanx.com. 120 IN CNAME na61-na62.wagbridge.alibaba.tanx.com.gds.alibabadns.com.
na61-na62.wagbridge.alibaba.tanx.com.gds.alibabadns.com. 120 IN	A 203.119.169.82

;; Query time: 414 msec
;; SERVER: 223.5.5.5#53(223.5.5.5)
```

**Comment by spirillen** [comment]
What is it exactly you want here? a removal? 

https://github.com/AdAway/adaway.github.io/blob/72ffceac56fdb09078bf2c6c69911cf7edb55f2e/hosts.txt#L11067-L11070

or help to redirect the request?

For an RPZ redirect rule it would look like this

```python
oms.cainiao.com.$ZONE    IN CNAME na61-na62.wagbridge.alibaba.tanx.com.gds.alibabadns.com.
```

**Comment by Franinc** [comment]
Forgot to attach a screenshot, AdGuard Home blocks `oms.cainiao.com` by rule `127.0.0.1 na61-na62.wagbridge.alibaba.tanx.com`
Is it appropriate to remove it from AdAway? If not, I can add a new custom filtering rule to ublock it alone.

![1111111](https://user-images.githubusercontent.com/26399054/129023795-ce8b1b35-33d2-4a30-8410-edf6c7f13f9b.jpg)

**Comment by spirillen** [comment]
Hmm, I can speak for my self, that domain is blocked in full (wildcard) on my adware but partially on the Tracking lists.

When I search the "Archives" https://github.com/Import-External-Sources/hosts-sources it appears the only one who else blocks the particular domain is https://github.com/blocklistproject/Lists

```shell
hosts-sources$ git grep '^na61-na62.wagbridge.alibaba.tanx.com'
data/adaway/domain.list:na61-na62.wagbridge.alibaba.tanx.com
data/blocklist_ads/domain.list:na61-na62.wagbridge.alibaba.tanx.com
```

But more widely the list is rather long. You can try this on a upgraded Windows (= Linux).

Download the "archive" and then run this command from within the repo

```shell
hosts-sources$ git grep 'tanx.com' | cut -d : -f 2 | sort -u
```

## My vote
I'm a bit in the middle to rule for or against a removal on this issue, in such cases I will stick to batter safe than sorry and keep a record until it's proven to be a FP. I do understand this can seems to be weird, but my believe is, nobody but the end-user self, should be judging what should be allowed to hunt you down (tracking, Spyware). The result is then the individual end-user should Whitelist an entry to allow the Cyber Criminal to track you down. Not some pizza eating Cola drinking dude from a dubious corner in a dark moist basement.

- Keep, you whitelist if you feel you need to, based on the knowledge of the consequences.

**Comment by spirillen** [comment]
PS @jawz101 could you tell us more about why the particular record is/was added? Would love to if you added the answer to https://mypdns.org/my-privacy-dns/matrix/-/issues/2483 as well.

**Comment by jawz101** [comment]
removed.  thanks
