### ISSUE TITLE
Blocking app.appsflyer.com & control.kochava.com breaks official app store platforms jump page

### ISSUE THREAD

**Issue by jdck** [AdAway/adaway.github.io#273]
It broke the official website download links of some software.

For example, Kaspersky VPN's Android Google Play link and iOS App Store link
https://www.kaspersky.com/vpn-secure-connection#installation

and Hotspot Shield
https://www.hotspotshield.com/vpn/vpn-for-android/

So it is proposed to remove app.appsflyer.com & control.kochava.com

**Comment by jawz101** [comment]
Not going to happen.  That's the purpose of this list.  If it breaks a webpage then the webpage should not break when their trackers are blocked.

**Comment by spirillen** [comment]
Also commented here: https://github.com/AdAway/adaway.github.io/issues/263#issuecomment-875849560
