### ISSUE TITLE
Blocking media-exp1.licdn.com prevents LinkedIn media preview loading

### ISSUE THREAD

**Issue by ilmonco** [AdAway/adaway.github.io#277]
media-exp1.licdn.com should be removed from blocklist because LinkedIn images, video preview, etc. won't be loaded.

**Comment by jawz101** [comment]
I'm not seeing that in the adaway blocklist

**Comment by ilmonco** [comment]
![_20210901_175848](https://user-images.githubusercontent.com/16099943/131704516-34d9f836-041c-4dfe-a99d-63080408c8ea.JPG)

**Comment by jawz101** [comment]
gotcha.  I removed all of the cedexis entries now
