### ISSUE TITLE
Netflix not loading

### ISSUE THREAD

**Issue by chatbuddy21** [AdAway/adaway.github.io#278]
The entry below seems to block Netflix on LG and Samsung smart tvs. It gives "Netflix Error NW-2-4". Removing the entry fixes the issue.

127.0.0.1 appboot.us-west-2.origin.prodaa.netflix.com 

--> this will block
   nrdp50-appboot.netflix.com
   nrdp51-appboot.netflix.com

**Comment by jawz101** [comment]
removed.  Sorry about that!
