### ISSUE TITLE
Netflix app not working on Roku

### ISSUE THREAD

**Issue by cbhiii** [AdAway/adaway.github.io#279]
Netflix app on Roku won't work without whitelisting this domain:

```
appboot.netflix.com
(blocked appboot.us-west-2.origin.prodaa.netflix.com)
```

Let me know if you need any other details. Thanks.

**Comment by jawz101** [comment]
I'm not seeing either of those

**Comment by cbhiii** [comment]
Weird. I did a domain search in Pihole and this ad list popped up. I’ll check again.

**Comment by jawz101** [comment]
> Weird. I did a domain search in Pihole and this ad list popped up. I’ll check again. 

> You might also try the update gravity thing too because I made a few changes this weekend after I dusted off my Roku to see what I was missing.  I can't believe how many new things I could find watching IMDbtv, Tubi.tv, and Pluto.tv.  most of them were video audience measuring companies (like Nielsen tv ratings).  But when I was done Pluto.tv tries to load its video ads and just started skipping them altogether.

**Comment by cbhiii** [comment]
Yeah I confirmed that when I search in Pihole (under Query lists). It shows me that long domain for some reason.

[![Match found in httpsadaway orghosts txt](https://user-images.githubusercontent.com/10853381/132007676-6bb731c1-6010-43a1-8fd0-fafa06c89534.png)
](url)

But, like you said that domain does not exist in the hosts list, so I have no idea how/why Pihole was blocking it and why I had to white list it.

**Comment by cbhiii** [comment]
Seems like some other issue not related to the list - closing.

**Comment by jawz101** [comment]
hm.  Interesting.  I know the ichnaea one doesn't break anything.  Maybe whitelisting nmtracking or presentation tracking ones to see if that works?

Google ichnaea for an interesting read.  It's like they named the server after a character in Greek mythology

**Comment by cbhiii** [comment]
Actually I did what you suggested and refreshed gravity after I was done investigating. ...and poof! It's gone now when I search for it. So who knows. Sorry to waste your time with it. Thanks for the time and upkeep on this list!
