### ISSUE TITLE
api.particle.io is being blocked 

### ISSUE THREAD

**Issue by No1089** [AdAway/adaway.github.io#28]
Our api; api.particle.io is being blocked by your host list. This is preventing our users from logging in if they have certain adblockers installed.

https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt 
13935: # [particle.io]
13936: 127.0.0.1 api.particle.io

Can you please remove it? We are an IoT company operating for 7 years - particle.io

Kind regards,
Chris

**Comment by alkingalking** [comment]
> Our api; api.particle.io is being blocked by your host list. This is preventing our users from logging in if they have certain adblockers installed.
> 
> https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt
> 13935: # [particle.io]
> 13936: 127.0.0.1 api.particle.io
> 
> Can you please remove it? We are an IoT company operating for 7 years - particle.io
> 
> Kind regards,
> Chris

**Comment by jawz101** [comment]
Thank you and I apologize for the interruption.

**Comment by No1089** [comment]
Thank you @jawz101!
