### ISSUE TITLE
False positive: audioboom.com

### ISSUE THREAD

**Issue by Zocker1999NET** [AdAway/adaway.github.io#280]
audioboom.com is used by some podcasters to publish their podcasts using this service. This site may also allows the creators to add ads to their podcasts themselves but I have not seen it yet that from this domain ads are served other than inside podcast files (as creators choose to do). Currently it breaks my podcast app trying to refresh a certain podcast hosted there.

**Comment by jawz101** [comment]
removed.  thanks
