### ISSUE TITLE
Remove ads in Pikashow

### ISSUE THREAD

**Issue by kryptobolt200528** [AdAway/adaway.github.io#283]
Hey please remove ads in the app pikashow its fetches ads via unity...

**Comment by kryptobolt200528** [comment]
solved 
add cdn.jsdelivr.net to list

**Comment by jimaek** [comment]
cdn.jsdelivr.net is a valid CDN for open source projects, by blocking it you will break thousands of websites

**Comment by spirillen** [comment]
And unblockiong it will permit shitload of tracking/spyware like

`https://cdn.jsdelivr.net/npm/@sheerid/jslib@latest/metrics.js`


Source: https://mypdns.org/my-privacy-dns/matrix/-/issues/1805

**Comment by kryptobolt200528** [comment]
hey for me till now...it hasn't broke any website....
