### ISSUE TITLE
[False positive] s.pinimg.com

### ISSUE THREAD

**Issue by AKorezin** [AdAway/adaway.github.io#295]
## Summary
Blocking domain `s.pinimg.com` makes https://www.pinterest.com/ unusable.

## Details
Unable to open pinterest pages, because it uses `s.pinimg.com` as domain to store scripts.
- https://s.pinimg.com/webapp/runtime-65b9ede60feeb10f.mjs

Introduced in https://github.com/AdAway/adaway.github.io/commit/6ce6cdc41e47071bc9677f4fde00145f485c6b32

**Comment by jawz101** [comment]
removed.  thanks
