### ISSUE TITLE
Add obs.line-scdn.net

### ISSUE THREAD

**Issue by danny-laa** [AdAway/adaway.github.io#296]
After blocking `obs.line-scdn.net`, advertisements won't load on chat tab of LINE (a popular instant messaging app in Korea, Japan and Taiwan).

Tested and worked on my device. Every feature of the app works fine AFAIK.

There are also some domains mentioned by others, but I didn't test them: https://github.com/StevenBlack/hosts/issues/1815

**Comment by danny-laa** [comment]
Turns out blocking this domain would prevent some other images from loading.

`a.line.me` maybe another domain I am investigating with. I have added it to my block list and I will update this ticket after several days.

**Comment by jawz101** [comment]
ok.  lemme know.  Sometimes it can be impossible to block first party content via DNS
