### ISSUE TITLE
add the domain to the blocklist

### ISSUE THREAD

**Issue by Olizja** [AdAway/adaway.github.io#297]
This - huq.io

https://blog.appcensus.io/2021/10/25/what-the-huq/ 
https://www.vice.com/en/article/5dgmqz/huq-location-data-opt-out-no-consent
https://www.bbc.com/news/technology-59346063

**Comment by jawz101** [comment]
1) I downloaded a bunch of apps that were detected to  have this sdk https://reports.exodus-privacy.eu.org/en/trackers/408/
 opened and observed traffic and not connected to a huq.io or huqindustries domain
2) I skimmed the articles and dl'd several of the apps mentioned and none connected to either domain
3) I read the bbc article and it says that Google issued a warning to these app devs to refrain from doing whatever it is they do.

I downloaded the Cisco Umbrella top 1 million DNS query list for today and searched for huq and found these entries.  Cross-referenced them w/ VirusTotal and they all communicate via Android apps in their sandboxing stuff.

> api.huqindustries.co.uk
> huq-query-loggers-california-3cec807da3e9dc0d.elb.us-west-1.amazonaws.com
> huq-query-loggers-europe-west1-32ef7f4bbf54ce27.elb.eu-west-1.amazonaws.com
> huq.io
> api.huq.io
> charles.huqindustries.co.uk

So I'll add them as soon as I can

I also found these additional domains while I was testing apps

> 
> mobile.measurelib.com
> nav.telematicsdirect.com
> pagead2.googleadservices.com
> sdk-monitoring.ogury.io
> api.monedata.iomericreceiver.cellrebel.com
