### ISSUE TITLE
TikTok captchas blocked

### ISSUE THREAD

**Issue by Lemmmy** [AdAway/adaway.github.io#298]
Hi,

The domain `verification-va.byteoversea.com` is blocked, which directly affects TikTok's anti-spam captcha page. Blocking this domain renders the entire site inaccessible:

![image](https://user-images.githubusercontent.com/858456/146103113-fbdab3dd-e200-459f-8120-27d9d1872667.png)

I believe the other subdomains of byteoversea (`mon-va`, `starling-va`, `vcs-va`) don't affect the captcha system and can remain blocked for now.

Related issues: #259, #80

Thanks

**Comment by jawz101** [comment]
Removed.  Thanks
