### ISSUE TITLE
api.particle.io is being blocked

### ISSUE THREAD

**Issue by No1089** [AdAway/adaway.github.io#30]
Hi there!

api.particle.io is part of your blocklist and causing major headaches at our support department.
Could you please assist in removing our API? We are a legitimate IoT company operating out of San Francisco.

https://www.particle.io for reference.

Kind regards,
Chris

**Comment by mstan** [comment]
Hi @PerfectSlayer ,

I am Matthew Stanley, one of our Enterprise Support Engineers at Particle. Happy to answer your questions.

Particle is an IoT platform for building internet connected products. Customers are not leveraging hosts blocks in Particle itself, but are impacted by having hosts blocking on their network.

All device and account management goes through our API. Our own console and mobile apps leverage api.particle.io. Users can also consume this API  directly for their own applications.

Particle is used both at scale and for prototyping developers. As our developers are often technical, many of them make use of adblocking services, such as the PiHole. Therefore, this addition caused significant issues for our customers consuming Particle on their own networks, as it restricted console, mobile, and API access to their account and devices.
