### ISSUE TITLE
Malicious domain

### ISSUE THREAD

**Issue by kickass42zer0** [AdAway/adaway.github.io#307]

**Comment by kickass42zer0** [comment]
Would like to report a domain
Note: If this isn't the proper place for this please advise where to make reports in the future.

Domain: intentionallylettuceponder.com
URL: https://intentionallylettuceponder.com/uvqsyhqi?key=e74506069444209769191bbc82166884

ESET reports: JS/Adware.TerraClicks.A application

**Comment by jawz101** [comment]
If it doesn't have to do with mobile app ads and trackers this list won't use it
