### ISSUE TITLE
[false positive] prevents watching videos on redbull.com

### ISSUE THREAD

**Issue by CynicusRex** [AdAway/adaway.github.io#309]
Concerning: [https://github.com/hectorm/hmirror/issues/14](https://github.com/hectorm/hmirror/issues/14).

On [https://www.redbull.com/int-en/films/valley-uprising](https://www.redbull.com/int-en/films/valley-uprising) the video keeps loading and yesterday it threw an “NETWORK_ERROR” error. Temporarily disabling hBlock fixed the problem, or watching it through Tor Browser.

[@hectorm](https://github.com/hectorm)
> It seems that the blocking of the `cs.liiift.io` domain is causing this issue.
> 
> That domain started to be blocked by AdAway in [AdAway/adaway.github.io@48583e7](https://github.com/AdAway/adaway.github.io/commit/48583e7b2c71451763dcd9501fd5a64c46b6b9d0). Could you report this in the AdAway repository? If that domain is removed from there it will also be automatically removed from hBlock.

**Comment by jawz101** [comment]
REMOVED.  THANKS
