### ISSUE TITLE
Remove domain aws.oath.cloud

### ISSUE THREAD

**Issue by bigdargon** [AdAway/adaway.github.io#311]
Domain `prod-us-west.fe.gdpr.aws.oath.cloud` is the CNAME of the domain name `aol.mydashboard.oath.com`. I am using nextdns and it is blocking the subdomains of `aws.oath.cloud`

Link: https://aol.mydashboard.oath.com/delete-my-account

Please check and remove if confused. Thank you!

**Comment by jawz101** [comment]
removed.  thanks
