### ISSUE TITLE
[False positive] Breaks streaming services

### ISSUE THREAD

**Issue by krbvroc1** [AdAway/adaway.github.io#313]
The following breaks streaming from vimeo subscription-based streaming service.

# [vhx.tv]
127.0.0.1 api.vhx.tv
127.0.0.1 collector.vhx.tv

**Comment by jawz101** [comment]
Can you give me an example of where this occurs?

**Comment by krbvroc1** [comment]
My wife was using Body Groove On-Demand  Android TV app and the commit you made 5 days ago 8dcfb1091bd74207a8e3a41faaa5b3aa41eb06e9 broke it. (I use pfSense)

**Comment by CTassisF** [comment]
www.wowpresentsplus.com (and its apps) is broken after api.vhx.tv was blocked. It works fine again after whitelisting only api.vhx.tv.

I guess it might be breaking other services that use Vimeo OTT too.

Screenshot: https://imgur.com/a/ty4IM6b

**Comment by jawz101** [comment]
removed.  Thanks
