### ISSUE TITLE
Adobe Marketing in 'DB Navigator'

### ISSUE THREAD

**Issue by KommX** [AdAway/adaway.github.io#326]
_DB Navigator_ is a popular app in Germany. It is using _Adobe Marketing Cloud_ to track its users via the domain `deutschebahn.sc.omtrdc.net`.
A detailed article can be found [here](https://www.kuketz-blog.de/db-navigator-datenschutz-faellt-heute-aus-app-check-teil1/).

As there are already other `omtrdc.net` subdomains in your list, I guess, you should also add this one.

**Comment by KommX** [comment]
Should I better open this issue in https://github.com/AdAway/AdAway ?

**Comment by jawz101** [comment]
added
