### ISSUE TITLE
Remove intercom.io

### ISSUE THREAD

**Issue by swrobel** [AdAway/adaway.github.io#33]
[Intercom.io](https://www.intercom.com/) is a useful live chat support platform. This is perhaps a bit more of a gray area than my previous request regarding Bugsnag, as one could argue that some of Intercom's behavior falls under trackers, but it definitely isn't ad-related, so I think it would help to clarify exactly what type of domains this list hopes to capture (with a product called AdAway I would expect it to just be Ad companies, but I could be wrong).

**Comment by jawz101** [comment]
I'm going to go ahead and remove it.  This big list change was all me and what I found not needed for me to use my phone.  That doesn't always translate to everyone and, considering you are developer, I respect your input.  Everything you've suggested has been "the tools in my toolbag" and they make sense.
