### ISSUE TITLE
api.instabug.com a bug reporter is getting blocked.

### ISSUE THREAD

**Issue by anwarelwakil** [AdAway/adaway.github.io#331]
**Describe the bug**
I noticed that our API api.instabug.com is blocked it is used for reporting bugs or crashes from inside mobile apps.

It isn't used to serve any ads
User consent is taken before sending the bug report

**Expected behavior**
Instabug bug reports and crash reports should not be blocked as those are sent by the users to report problems in the application.

**Comment by anwarelwakil** [comment]
@PerfectSlayer Thank you for clarifying this was initially discussed #68. Can we please check if it got readded by mistake as this blocks end-users from submitting feedback to the application developer?

**Comment by jawz101** [comment]
removed thanks
