### ISSUE TITLE
Junk email from adaway.org

### ISSUE THREAD

**Issue by qianbinbin** [AdAway/adaway.github.io#337]
I got a junk email from NcDolbnx.pjscp@adaway.org:

<img width="799" alt="截屏2022-06-28 11 10 23" src="https://user-images.githubusercontent.com/7856168/176084086-087f31da-b886-4a45-8c69-0c663f83ff50.png">

Did the domain get attacked?

**Comment by PerfectSlayer** [comment]
Thanks for the heads-up! 
I am not aware of a such thing but I will have a look to the hoster/dns provider...

I might also be fake mail headers 😕

**Comment by qianbinbin** [comment]
I did some research and find that, the sender of an email, which is `From` field in SMTP headers, can be faked easily.

The internet is so dangerous, for years I check the sender by its domain 😢, you can close this issue if I got wrong.

**Comment by PerfectSlayer** [comment]
Yeah, I don't think their is SPF or DKIM on the domain so it will be easy to fake it.

In the meantime I didn't see any issue on my side with the hosting. I'll close the issue. Thanks for the report!
