### ISSUE TITLE
False positive: pi.pardot.com

### ISSUE THREAD

**Issue by Bertaz** [AdAway/adaway.github.io#338]
info.ammex.com CNAME is go.pardot.com which CNAME is pi.pardot.com
pi.pardot.com is blocked so info.ammex.com is blocked

Example site: https://info.ammex.com/ammex-bx3-black-nitrile-industrial-latex-free-disposable-gloves-case-of-1000-em

**Comment by jawz101** [comment]
I likely will not remove it at this point.  If a site is using a marketing company's SDK in a way that causes breakage if the marketing code is blocked, they should probably change their implementation.

**Comment by maurice-w** [comment]
pi.pardot.com is also used by ISRG, the nonprofit behind Let's Encrypt:

https://letsencrypt.org/opt-in/

```
Name                           Type   TTL   Section    NameHost
----                           ----   ---   -------    --------
outreach.abetterinternet.org   CNAME  15    Answer     go.pardot.com
go.pardot.com                  CNAME  15    Answer     pi.pardot.com
```

Please reconsider removal.
