### ISSUE TITLE
mparticle.uc.cn should not be blocked

### ISSUE THREAD

**Issue by MkQtS** [AdAway/adaway.github.io#341]
https://github.com/AdAway/adaway.github.io/blob/662452dbc601e2816f64118eb6b529511f19b377/hosts.txt#L10286

mparticle.uc.cn provides some articles/news to UC browser users, like [this](https://mparticle.uc.cn/article_org.html?uc_param_str=frdnsnpfvecpntnwprdssskt&sm_article_id=18217717346989190304#!wm_cid=498224002232224768).

I didn't find any evidence that this domain is related to advertising.

**Comment by MkQtS** [comment]
> mparticle is an tracking company https://www.mparticle.com/

I don't know why they used the word `mparticle` in this domain. But it seems that `mparticle.uc.cn` is just a subdomain of `uc.cn` and has no relationship with `mparticle.com`. They are two domains running by different companys actually.

The domain, `mparticle.uc.cn`, is  just used as front-end webpage to repreasent their articles, like the link I posted earlier. (However, the url do contain some tracking params, they are automatically generated even after manually removing them.)

**Comment by jawz101** [comment]
I understand they are different companies.  mParticle is a company that offers a product for other companies to track users.  If a company self hosts that product or redirects traffic thru a doman w/in their subnet, it is still utilizing that tracking product.  For example, Amazon uses a product made by a company called [Forrester ](https://www.forrester.com/bold) using a product called Forrester Logging Service[ to track consumer interaction with their products](https://docs.aws.amazon.com/workspaces/latest/adminguide/workspaces-port-requirements.html).  Amazon directs this traffic to fls-na.amazon.com (North America) and fls-eu.amazon.com (European Union) among others:

```
fls-na.amazon.com
fls-na.amazon-adsystem.com
fls-eu.amazon.co.uk
fls-eu.amazon.com
fls-eu.amazon.de
fls-na.amazon.ca
fls-eu.amazon-adsystem.com
fls-na.amazon.com.mx
fls-eu.amazon.es
fls-eu.amazon.fr
fls-fe.amazon.co.jp
fls-eu.amazon.in
fls-eu.amazon.it
fls-eu.amazon.com.tr
fls-eu.amazon.nl
fls-eu.amazon.ae
fls-fe.amazon.com
fls-eu.amazon.pl
fls-na.amazon.com.br
fls-eu.amazon.eg
fls-eu.amazon.se
fls-fe.amazon.com.au
fls-eu.amazon.sa
fls-fe.amazon.sg
fls-fe.amazon-adsystem.com
fls-cn.amazon.cn
fls-eu.amazon.ca
```

so does Google's Doubleclick (there are thousands of these with this naming convention)

```
fls.doubleclick.net
4704202.fls.doubleclick.net
5290727.fls.doubleclick.net
6451349.fls.doubleclick.net
8980432.fls.doubleclick.net
8397396.fls.doubleclick.net
8666735.fls.doubleclick.net
9910951.fls.doubleclick.net
2906542.fls.doubleclick.net
1620481.fls.doubleclick.net
10291144.fls.doubleclick.net
1359940.fls.doubleclick.net
6372968.fls.doubleclick.net
```

It is not a coincidence that UC uses 'mparticle' in one of their own subdomains on their own domain.  [mParticle even gives documentation on why a client would want to do this](https://docs.mparticle.com/developers/sdk/android/prevent-blocked-http-traffic/)

**Comment by jawz101** [comment]
... I likely won't remove it

**Comment by MkQtS** [comment]
It's OK, I respect that.
