### ISSUE TITLE
Blocking socialize.eu1.gigya.com breaks login on videoland.com

### ISSUE THREAD

**Issue by EchoDev** [AdAway/adaway.github.io#343]
Blocking socialize.eu1.gigya.com breaks login on videoland.com (and probably more sites)
The us version (socialize.us1.gigya.com) is not on the list but they used to be together on adaway hosts.txt. 

Seems like this happened before and the domain got removed from the list, see #53 

https://github.com/AdAway/adaway.github.io/blob/662452dbc601e2816f64118eb6b529511f19b377/hosts.txt#L4677

**Comment by jawz101** [comment]
thanks.  I pulled in your change
