### ISSUE TITLE
[False positive] images.salsify.com

### ISSUE THREAD

**Issue by 0xadada** [AdAway/adaway.github.io#349]
Salsify.com is a service for hosting product content for brand who are sold online. We don't use that domain for tracking, its just a CNAME for Cloudinary who does image hosting for us (I work at Salsify, and my PiHole blocked our domain and i noticed it as an ublock origin/AdBlock user).

**Comment by jawz101** [comment]
removed.  Thanks!

**Comment by 0xadada** [comment]
thanks
