### ISSUE TITLE
removal of cdns.gigya.com breaks euroinvestor.dk and berlingske.dk logins

### ISSUE THREAD

**Issue by philipsoeberg** [AdAway/adaway.github.io#351]
commit https://github.com/AdAway/adaway.github.io/commit/4e37a5c67ddc750295b1a6f5556e8bbde3ce66e1 seem to break news site berlingske.dk and portfolio management site euroinvestor.dk.

The missing script seem to origin from https://cdns.gigya.com/js/gigya.js?apiKey=<long key> and without it, login features on the two domains won't function.

**Comment by jawz101** [comment]
removed.  thanks
