### ISSUE TITLE
Our map and APIs are being blocked

### ISSUE THREAD

**Issue by gopi-ar** [AdAway/adaway.github.io#36]
Hello,

We offer maps & geocoding (address) APIs to over 50k developers and do not have anything but Google Analytics & Intercom (chat) on our website. We woke up today to find our map tile servers and our US API endpoint listed on your list.

Could you please help us remove this?

```
us1.locationiq.com
maps.locationiq.com
```

Thanks,

**Comment by jawz101** [comment]
removed.  I took a look at your site, privacy policy, developer documentation and it looks like the right sort of location service
