### ISSUE TITLE
Mobile apps don't work because API is being blocked

### ISSUE THREAD

**Issue by ustav** [AdAway/adaway.github.io#38]
Hi, 

Immobilienscou24 mobile apps stop working because our apis are being blocked. I've created a pull request to remove domains from blacklist. 

We get more and more angry users because app just can't load content.

These domains are absolutely crucial for applications to work:
- api.finanzen.immobilienscout24.de
- api.mobile.immobilienscout24.de
- api.recommendation.immobilienscout24.de

Could you please remove them from blacklist?

**Comment by jawz101** [comment]
removed app breakage entries
