### ISSUE TITLE
Remove gumtree.com

### ISSUE THREAD

**Issue by PedroLamas** [AdAway/adaway.github.io#40]
As far as I'm aware, www.gumtree.com is just a website to site for free classified ads, mostly used by people to sell used items!

**Comment by spirillen** [comment]
> free classified ads

To my spell-book for vanish the spells removes all ads like magic 

Jokes to the side, do the domain hosts ads or not?

**Comment by PedroLamas** [comment]
On their own website yes (that's the whole point of their website!), but I don't believe they provide ads to other websites (like google ads or other platforms do).

**Comment by spirillen** [comment]
By the way, congrats by leaving the EU :clap: :gb:

**Comment by spirillen** [comment]
The ads on this domain actually seems to come from third party `cdn.adsafeprotected.com`

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +48 | ##.right |  | `www.gumtree.com` |  | dom | `https://www.gumtree.com/` |
| +22 | ##.fixed-bottom.gdpr-banner.notification |  | `www.gumtree.com` |  | dom | `https://www.gumtree.com/` |
| +2 | ##.ad-slot |  | `www.gumtree.com` |  | dom | `https://www.gumtree.com/` |
| +2 | ###homeSideAd |  | `www.gumtree.com` |  | dom | `https://www.gumtree.com/` |
| +1 | \|\|gumtree.com/ycxwzbcsxennhrkcxhr.js | -- | `www.gumtree.com` | 1 | script | `https://www.gumtree.com/ycxwzbcsxennhrkcxhr.js` |
| +1 | \|\|adsafeprotected.com^$3p | -- | `www.gumtree.com` | 3 | script | `https://cdn.adsafeprotected.com/iasPET.1.js` |
| +1 | scorecardresearch.com/beacon.js | << | `www.gumtree.com` |  | script | `https://sb.scorecardresearch.com/beacon.js` |
| +1 | \|\|scorecardresearch.com^$3p | -- | `www.gumtree.com` | 3 | script | `https://sb.scorecardresearch.com/beacon.js` |
| +1 | \|\|videoplayerhub.com^$3p | -- | `www.gumtree.com` | 3 | script | `https://gumtree-com-uk.videoplayerhub.com/galleryplayer.js` |
| +1 | \|\|gumtree.com/ycxwzbcsxennhrkcxhr.js | -- | `www.gumtree.com` | 1 | script | `https://www.gumtree.com/ycxwzbcsxennhrkcxhr.js` |
| +1 | \|\|adsafeprotected.com^$3p | -- | `www.gumtree.com` | 3 | script | `https://cdn.adsafeprotected.com/iasPET.1.js` |
| +1 | \|\|videoplayerhub.com^$3p | -- | `www.gumtree.com` | 3 | script | `https://gumtree-com-uk.videoplayerhub.com/galleryplayer.js` |
| +1 | googletagservices.com/gpt.js | << | `www.gumtree.com` |  | script | `https://www.googletagservices.com/tag/js/gpt.js` |
| +1 | \|\|googletagservices.*^ | -- | `www.gumtree.com` | 3 | script | `https://www.googletagservices.com/tag/js/gpt.js` |
</details>

**Comment by PedroLamas** [comment]
Maybe I'm not explaining myself correctly... I and a lot of other people access www.gumtree.com to buy and sell stuff, but you have the domain blacklisted here: https://github.com/AdAway/adaway.github.io/blob/5d5ead9edde26f0aceb249ccf06a9cfef6d03159/hosts.txt#L7974



> By the way, congrats by leaving the EU 👏 🇬🇧

Not sure if you are serious or being ironic with this, but in any case, I try to stay away from discussing politics in GitHub.

**Comment by jawz101** [comment]
removing it.  Thanks
