### ISSUE TITLE
Incorrect domain added *wbx2.com

### ISSUE THREAD

**Issue by c0rce** [AdAway/adaway.github.io#41]
proximity-a.wbx2.com
proximity-one-static.wbx2.com

*.wbx2.com is a domain used by Cisco Webex to allow wireless pairing between video conferencing devices and apps. By blocking these domains, functionality is lost, can these be removed?

This domain is documented as required by Cisco: https://help.webex.com/en-us/WBX000028782/Network-Requirements-for-Webex-Teams-Services

**Comment by jawz101** [comment]
removed.  That's very handy they have a support article describing them.  I suppose they get a lot of system admins who want to know what the traffic is because "proximity" is one of those words that implies privacy risk.

**Comment by llacb47** [comment]
Close?
