### ISSUE TITLE
`mediaset.[ net | it ]`

### ISSUE THREAD

**Issue by AnonymousPoster** [AdAway/adaway.github.io#47]
Hi guys, I've got an issue that I'm not completely able to solve for my self as there is a language barrier that need to be broken down, Italian.

## The pray :pray: 
But since I can find a few of the domains within your lists I hope we all can cooperate and help each other to optimize this for all.

## Intro
The initial issue is posted here: https://www.mypdns.org/ticket/65 and there are two related issues https://www.mypdns.org/ticket/190 and https://www.mypdns.org/ticket/191. (There was split up to follow the guidance of issue posting (1 domain = one issue)) 

@Khrin Have posted [some answers](https://github.com/easylist/easylist/issues/4887#issuecomment-584827877) to this on [EasyList](https://github.com/easylist/easylist).

## Domains
The domains in question is:
```
enabler.datalake.mediaset.it
hbbtv.mediaset.net 
```

```
data/adaway/domain.list:enabler.datalake.mediaset.it
data/adaway/domain.list:hbbtv.mediaset.net
data/adaway/domain.list:webtrekk.mediaset.net
```

And from a few other BlackLists projects I've found these

```
data/notrack/blocklists/domain.list:webtrekk.mediaset.net
data/mvps/domain.list:webtrekk.mediaset.net
```

So the only domain in common is `webtrekk.mediaset.net` 

## The question :question: 

Why have you chosen to also block

```
enabler.datalake.mediaset.it
hbbtv.mediaset.net
```

For what I can come up with, then `hbbtv.mediaset.net` apparently is a connection bridge between a [HBBTV](https://www.hbbtv.org/) enabled TV and the given TV-channel you currently watch.
Which of curse never should happens unless you explicitly request the device to do so, as it shares your IP and the fact you own (uses) a HBBTV enabled (un)smart-TV or other device as this is leaving a involuntary trail of Tracking (Spying) on you.

Kind of the same way as you keep having requests to [`dr-massive.dk`](https://github.com/mypdns/matrix/issues/26) without ever having used that shit as it violates your privacy, but the DNS query comes every time you watch the air bone TV-signal of any of the `dr.tv` channels.

For the `enabler.datalake.mediaset.it` I feel like I weakly can recall, that this domain is used to enables you to login to your `mediaset.net` user account, but also _TRACKING_

Moved from: https://github.com/AdAway/AdAway/issues/1594

**Comment by jawz101** [comment]
I'm removing all of them.  looks like it came in from a merge I did to the MATS [list back in Feb 2019 ](https://github.com/jawz101/MobileAdTrackers/commit/daa8fa610cf43069b9dd8d9b28de56d86cd94e22#diff-85cf4e6d42a71e693fd780c8b29accdd) from this list https://github.com/bigdargon/hostsVN/ which they had added just before with this commit
https://github.com/bigdargon/hostsVN/commit/b527385519cf66446c2d66420e053a415d5d0f42#diff-85cf4e6d42a71e693fd780c8b29accddL8299-L8300

**Comment by AnonymousPoster** [comment]
From what I understand in your post at https://github.com/bigdargon/hostsVN/issues/156 you have misunderstood my intention on this issue. 

My intention wasn't to necessarely have them removed, but figure out why there where listed in your list as the only source I have found and whether it would breaks the common use of streamed services from `mediaset.it`, as I would hate to break things I don't know anything about.

But as mentioned in the above reference I'm awaiting the response from the originating source.

**Comment by jawz101** [comment]
I originally got these entries from that bigdargon hostfile so if it needs further discussion I would start with them.  From what I understand, you say tracking that connects to `hbbtv.mediaset.net` is an opt-in preference so it is not really necessary to block if you can opt out, right?  And blocking `enabler.datalake.mediaset.it` breaks a login screen.  So, there isn't any reason for a mobile ad/tracker blocklist to block those 2 subdomains.

**Comment by AnonymousPoster** [comment]
AAhh that what's went wrong :+1: 

> I feel like I weakly can recall, that this domain is used....

That should have been understood as:

I'm absolutely not sure, but isn't there something about that.. I might recall = <=10% weight :smiley: 

You know when things are getting to old and fluffy, but you have the sensation of remembering something, but you are absolutely not sure on anything :thought_balloon:

**Comment by jawz101** [comment]
Ah.  Well, as I am not from Italy and Mediaset sounds like a regional product, I leave it to you to tell me if it is ok to block or not.  :) That addition was because I _do_ want to make the list more "globally applicable" since I am in the United States and I do not get exposed to those domains.

It almost sounds like the [Nielsen TV Ratings](https://www.nielsen.com/us/en/solutions/measurement/television/) company of Italy.

**Comment by AnonymousPoster** [comment]
Damned that was a ugly tracker you exposed there... you should have reported that one on https://github.com/mypdns/matrix :smiling_imp: 

But done that for you :smiley: https://github.com/mypdns/matrix/pull/280
