### ISSUE TITLE
Whitelist request for api.metrics.heroku.com

### ISSUE THREAD

**Issue by mr-perseus** [AdAway/adaway.github.io#52]
**Describe the third party app**

App Metrics in Heroku Dashboard: https://dashboard.heroku.com/apps

**Describe the compatibility issue**
App Metrics on Heroku Dashboard are not loaded. See: https://help.heroku.com/A1BZM6QC/why-do-i-see-item-could-not-be-updated-retrieved-unknown-error-on-the-dashboard

**Workaround**
Whitelist the following domain:

api.metrics.heroku.com

**Comment by jawz101** [comment]
removing.  please close if it looks good.  thanks
