### ISSUE TITLE
socialize.us1.gigya.com addition

### ISSUE THREAD

**Issue by nwalke** [AdAway/adaway.github.io#53]
Hey there!  I recently noticed an app became unusable when my network level ad blocker was turned on... I traced it back all the way to this project and in particular, this commit: https://github.com/AdAway/adaway.github.io/commit/e025400717910910a994fc051f90c5a340b71af1

The app is silly for just totally breaking when that host is unavailable, however, I don't think the socialize.us1.gigya.com and socialize.eu1.gigya.com domains should be in this list.  These are not ad serving domains and it looks like were added maybe a bit hastily.  These domains seem to typically be used for customer engagement within an app (login, comments, ratings, loyalty).  You can read more about them here: https://developers.gigya.com/display/GD/Social+Engagement+Deprecation

I think their removal from this list would make the most sense.

**Comment by jawz101** [comment]
This list is for ads and trackers and Gigya's business is Customer Identity Management- hardly hastily added.

When an sdk says it gathers [behavioral data](https://developers.gigya.com/display/GD/Signals) and enables [profiling users](https://developers.gigya.com/display/GD/Progressive+Profiling#ProgressiveProfiling-ProgressiveProfiling), that is tracking.

But if it's breaking a login, can you clarify what type of app it is?

**Comment by nwalke** [comment]
I see your point and am happy to move along should you chose not to remove it.  I would much rather lists like this exist than not.

The app in question is the irobot home app (for controlling their line of robot vacuums).  It's silly that the app just completely fails to work because of this, but it doesn't.  My guess is that they only use this for logins as there wasn't any gamification/ratings/reviews or any social features inside the app.  Completely understandable if the answer is "no" because we shouldn't bow down to one app.  

Thanks for the conversation around this though!

**Comment by jawz101** [comment]
well I'm removing it if it breaks logins.  The actual product is made by SAP- a reputable big ERP company.

**Comment by nwalke** [comment]
Thanks again for the conversation around this.  Much appreciated!

**Comment by jawz101** [comment]
I like chatting about this stuff.  I figure we all agree on what is or isn't an ad or tracking thing.  This is just one of those "maybe?" ones

**Comment by spirillen** [comment]
Hey @jawz101 A friendly question...

I'm trying to understand your words vs the actions. I'n this comment you write all the right stuff making me suggestion a marriage :ring: :bride_with_veil: :man_in_tuxedo: 

> This list is for ads and trackers and Gigya's business is Customer Identity Management.

> When an sdk says it gathers behavioral data and enables profiling users, that is tracking. Or it at least enters a gray area where it's for single sign-on things... with optional user profiling.

> Log into Nike app w/ Facebook = Facebook now knows you like Nike. And maybe Nike now knows all of your FB likes, age, profile pic, and sends you targeted marketing. That's where if it doesn't break logins, I favor blocking. Single signon is the user-facing perk, demographics gathering is the business-facing feature.

Yet you give in for the same perks who owns your ass and know more about everyone, than they do them self in 1c1a2e9 , now I'm filing for devorce :wedding: :rofl: 

The question is.... Why did you give up, and gave into the domain? because somebody have miss-written there code, breaking there own app? or?  I'm bit confused and would like to understand these opposed actions and words.
