### ISSUE TITLE
api.band.us is the biggest GroupMessage app in Korea.

### ISSUE THREAD

**Issue by dosuser** [AdAway/adaway.github.io#54]
2020.1.2 blocked api.band.us is a domain of BAND a popular app in Korea.
**api**.band.us is the main rest API domain to service.
so, many people suffering problems.

you can see it in below 
https://play.google.com/store/apps/details?id=com.nhn.android.band&hl=en_US
downloaded 50,000,000+

Problem commits.
https://github.com/AdAway/adaway.github.io/commit/9db9a33772a7ac76e7ce9c710d07226a12b8e8

@jawz101 
https://github.com/jawz101/MobileAdTrackers/commit/12e7354d39be0b384654a1026649d97d29be8d35
​

**Comment by jawz101** [comment]
removed.  please close if it looks ok.  Thank you and I apologize for the inconvenience.  I'm tracking down how that commit was entered and if it came from elsewhere I will let them know of the breakage

**Comment by dosuser** [comment]
Thank you,  I checked. have a good day.
