### ISSUE TITLE
Blocking of "ns.exitgames.com" breaks games that use the Photon multiplayer platform

### ISSUE THREAD

**Issue by NamelessVoice** [AdAway/adaway.github.io#58]
My router has ad-blocking software which blocks ads at a network level, and one of the hosts files it uses is the AdAway one.
It recently added the domain "ns.exitgames.com", which is used by the Photon multiplayer platform. Blocking that domain breaks any multiplayer games which use that provider.
I noticed it on Distrust, a PC game (and it worked last week, so the change must have been recent), but it sounds like the provider also provides multiplayer to Android games as well.

**Comment by Techjar** [comment]
This explains my troubles with Rec Room, as it also uses the Photon platform.

**Comment by jawz101** [comment]
fixed
