### ISSUE TITLE
[workaround-available] https://appcenter.ms/ being blocked - false positive? 

### ISSUE THREAD

**Issue by zvargams** [AdAway/adaway.github.io#63]
**Describe the third party app**
 - Name: https://appcenter.ms/ and applications hosted there

**Describe the compabitily issue**
Seems like the following two domains being blocked will break some applications hosted at https://appcenter.ms/ - which seems to be a legitimate Dev site owned by Microsoft

# [hockeyapp.net]
127.0.0.1 gate.hockeyapp.net
127.0.0.1 sdk.hockeyapp.net

**Workaround**
If applicable, describe the whitelist domains to add to fix the issue:

After whitelisting these two, app started to work properly:

gate.hockeyapp.net
sdk.hockeyapp.net

--

Is there any particular reason to have these blocked? Please consider removing those two domains. Thank you.

**Comment by jawz101** [comment]
@zvargams Do you have an example of an app that experiences user-facing breakage I can test?

**Comment by zvargams** [comment]
Hello @jawz101 we have an internal (MSFT) application which updates itself from there, and unless I whitelist those two hockeyapp.net domains, the process fails (obviously.)

**Comment by spirillen** [comment]
Hi @zvargams are you sure you need to hack the protection by circumvent `sdk.hockeyapp.net`?

And as @jawz101 says, any public facing apps that can work without these trackers? and therefor to be considered badly coded apps?

**Comment by ggazebo** [comment]
AppCenter is typically used for distributing internal apps that are not available publically. HockeyApp is the product name before it was acquired by Microsoft, and it is legitimately associated with AppCenter.

While telemetry collection is an optional part of integration, there is a very legitimate use case of providing app updates for internal, private apps. This is akin to blocking a non-Google app store.

**Comment by jawz101** [comment]
Then I would recommend not using this list in a corporate environment.

**Comment by zvargams** [comment]
@jawz101 

All due respect, I tend to disagree with you.

1. This is a blacklist and not a whitelist, right? Also it has been proven that 

gate.hockeyapp.net
sdk.hockeyapp.net

are legitimate URLs, therefore I'm totally confused why are they blocked here.

**Why were these blocked in the first place? Do you have any reports of malicious activities?** 

2. Surely in a corp environment we do not rely on AdAway. However you might have heard about a recent virus outbreak, it is really a tiny one, just a few billion people are staying at home and working from there. Where they usually have a privately owned router with a privately configured adblocker.

Therefore having these legitimate URLs blocked can lead to a disruption.

**Comment by spirillen** [comment]
As previously stated, you have chosen to disrupt your self. 

> While telemetry collection is an optional part of integration

Any Microsoft product... there are no legitimate use, it only spyware(telemetry), trackware and users can't decider for them self if they like to participate in any tracking without network skills above average.

**Comment by zvargams** [comment]
@spirillen  

What telemetry are you insinuating here?

The dogfood app I'm using works totally fine with adblock. The only failing part is the self-update feature, which would like to download the nightly builds, but the URL being blocked.
