### ISSUE TITLE
[hosts.txt] Wrong domain name in hosts.txt

### ISSUE THREAD

**Issue by 0x112** [AdAway/adaway.github.io#64]
```
# [ip-api.com]
127.0.0.1 ip-api.com
```
ip-api.com is not an advertising domain, hope to remove it. Thanks.

**Comment by jawz101** [comment]
unless it breaks something it stays.

**Comment by pexcn** [comment]
https://ip-api.com is a website that looks up IP addresses.

**Comment by jawz101** [comment]
describe breakage

**Comment by spirillen** [comment]
@pexcn it is a tracking domain..... it tracks al your movements and whereabouts hidden within aps

#25, https://github.com/AdAway/adaway.github.io/pull/72 and https://www.mypdns.org/T601
