### ISSUE TITLE
False positive Google subdomains

### ISSUE THREAD

**Issue by mKoonrad** [AdAway/adaway.github.io#66]
```
ads.google.com
adservice.google.com
```

These subdomains are used only for Google Ads panel - not showing ads/trackers.

**Comment by llacb47** [comment]
Wrong, go to google homepage and a request is made to `adservice.google.com`.

**Comment by spirillen** [comment]
Are you working for [Google](https://www.mypdns.org/w/domain/google.com/)?

**Comment by jawz101** [comment]
This is like that other issue from a guy working for Microsoft saying he can't use their analytics suite at work.  This list is of unnecessary domains observed by phones doing regular user stuff so it's not meant for those who want to connect to the domains it tries to block.
