### ISSUE TITLE
False Positive: a bug reporting tool

### ISSUE THREAD

**Issue by msoliman** [AdAway/adaway.github.io#68]
I noticed that our API `api.instabug.com` is blocked. [Instabug](instabug.com) is used for reporting bugs or crashes from inside mobile apps.

* It isn't used to serve any ads
* User consent is taken before sending the bug report

**Comment by llacb47** [comment]
Similar to crashlytics? Those types of services are blocked in this list.

**Comment by jawz101** [comment]
removing instabug.com entries.  Looking over their site, their product is very much for bug reporting and user feedback and I didn't see anything in the marketing or developer documentation that felt like a privacy problem.

I'm a fan of metrics and diagnostics if it sounds right and this sounds like a good company.

And this looks like the CTO which is neat.  Thank you for bringing this to my attention.

**Comment by spirillen** [comment]
Without having read the entire site, I stumble on this quote, which make me think surveillance of the masses. (Tracking)

> in-app surveys, and real-time user feedback

This line makes me think **Branding** tool (AdWare)

> Understand what really matters to your customers with an intuitive in-app feedback experience through feedback forms, contextual mobile surveys, and in-app chat.

So here is the Q to @msoliman: Can you show me just 1 prove that a user would have to **_opt-in_** and that it needs to be on a voluntary basis for using the app you are _integrated_ into and that the "app" are not allowed to block the usage without accepting the surveillance tool from you?

Please post your answer here: <https://www.mypdns.org/T602>

**Comment by msoliman** [comment]
@Spirillen Sorry for my late reply. I missed your earlier message.

Sure. I see you're talking here about two products that we offer: Bug Reporting and Surveys.

1- For Bug Reporting:
- The user gets to invoke our SDK, it doesn't get triggered automatically. There are different ways of invoking it based on the app configuration. More details [here](https://docs.instabug.com/docs/ios-invocation)
- When the SDK gets invoked, the user's confirmation is needed before proceeding. Screenshot attached
<img width="176" alt="Screen Shot 2020-05-07 at 2 31 12 AM" src="https://user-images.githubusercontent.com/2641429/81242155-b215c580-900c-11ea-9098-be5a485919e6.png">


2- For Surveys:
- When a survey shows up in the application, the user needs to opt-in to take it. Otherwise, the survey can be dismissed
<img width="175" alt="Screen Shot 2020-05-07 at 2 38 24 AM" src="https://user-images.githubusercontent.com/2641429/81242165-b7731000-900c-11ea-9957-c175105169fe.png">


Hope that this answers your question. Answer also posted here: https://www.mypdns.org/T602#7652
