### ISSUE TITLE
Domain reports

### ISSUE THREAD

**Issue by PerfectSlayer** [AdAway/adaway.github.io#69]
Hello again @jawz101 (sorry to bother you so many times lately...)

I can read from the help page bundled in the app that we recommend to report any new found domain to the hosts-file.net forum. 

> <h2>It does not block ads in application XYZ!</h2>
> <p>Some hostnames may be missing in the provided hosts files from the <cite>Hosts Sources</cite> or the application has bundled the images to provide ads without accessing the internet.<br/><br/>
> You can log DNS requests (Menu-&gt;Log DNS Requests) from AdAway to find out which additional hostnames have to be blocked.
> <br/><br/>Add the suspicious hostnames to your own Blacklist by long pressing the entries in the Log and report these hostnames when you have verified them in the Forum <a href="http://forum.hosts-file.net/viewforum.php?f=9">Hosts Inbox</a> of <a href="http://hosts-file.net">hosts-file.net</a>.</p>

As it is closed, would you like users report adware domain on this GitHub or do you have any other place in mind? Another solution could be to simply remove the report part for the help page.

What would you prefer?

**Comment by jawz101** [comment]
I just say report it as an issue here and I'll look into it

**Comment by PerfectSlayer** [comment]
Alright, thanks.
I hope everything is set for the hosts replacement now...
