### ISSUE TITLE
False positive for Help Scout

### ISSUE THREAD

**Issue by 8bitPit** [AdAway/adaway.github.io#70]
Hi everyone, I’m and Android app developer who wants to integrate helpdesk software to improve customer support. Today I discovered that AdAway blocks Help Scout’s Beacon API. It lets users access our knowledge base and ask us for help. However, this site doesn’t serve ads. Could this be a false positive?

The following domains are currently blacklisted by AdAway:
```
# [helpscout.net]
127.0.0.1 beacon-v2.helpscout.net
127.0.0.1 beaconapi.helpscout.net
```

I also found an article from Help Scout about this, might be interesting for you: 
https://docs.helpscout.com/article/911-beacon-ad-blockers

Note: I’m not working for Help Scout, I’m just one of their customers.
Wish you a nice weekend and stay safe 😊

**Comment by jawz101** [comment]
removed.  Thanks

**Comment by 8bitPit** [comment]
Awesome, thank you very much!
