### ISSUE TITLE
Remove Airbrake from hosts

### ISSUE THREAD

**Issue by thompiler** [AdAway/adaway.github.io#73]
Hi AdAway team,

(Full disclosure: I work at Airbrake.)

Airbrake is an application monitoring tool (error monitoring, deploy tracking, performance monitoring) similar to Bugsnag which was removed recently (https://github.com/AdAway/adaway.github.io/issues/29). Error monitoring is an essential tool for app developers to fix bugs that pop up in their code. It doesn't track users or take screenshots of users' actions. The only way user data would be sent to Airbrake would be if the end user directly ran into an error in the developer's app, then if the developer chooses to record it, the end user's email address and ID can be sent to aid in debugging.

Since Airbrake is not an advertising tracking or malicious service, we think it should be removed from the [`hosts.txt`](https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt#L2669-L2674) file in this repo. The AdAway project is also used in compiling the block list for https://github.com/StevenBlack/hosts which is how we came across this project.

Relevant links for reference:
 - [Homepage](https://airbrake.io/)
 - [Privacy policy](https://airbrake.io/privacy)
 - [Terms of service](https://airbrake.io/terms)

Let us know if we can answer any questions. Thanks!

**Comment by thompiler** [comment]
Thank you @jawz101! 👍

**Comment by jawz101** [comment]
you're welcome
