### ISSUE TITLE
cdn.wootric.com

### ISSUE THREAD

**Issue by beerisgood** [AdAway/adaway.github.io#74]
cdn.wootric.com is needed for Zoom in web browser

Without the whole site usage break

**Comment by jawz101** [comment]
I just went to https://zoom.us/test and tried it while observing [TCPView](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview) and didn't see any connections to that domain

**Comment by beerisgood** [comment]
> I just went to https://zoom.us/test and tried it while observing [TCPView](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview) and didn't see any connections to that domain

I found the domain in PiHole, blocked by your list.
It's needed for using group chat's

**Comment by jawz101** [comment]
removed
