### ISSUE TITLE
cnbc.com Live Audio

### ISSUE THREAD

**Issue by ACMEd** [AdAway/adaway.github.io#79]
Visit https://www.cnbc.com/live-audio/ and click play. The audio stream doesn't work unless this domain is whitelisted:

`aa5dbe242ad94ceba164ecf25b68c84e.mediatailor.us-west-2.amazonaws.com`

**Comment by llacb47** [comment]
That's a tunein stream domain, don't know why it was blocked.

**Comment by jawz101** [comment]
removed
