### ISSUE TITLE
Tiktok DMs blocked

### ISSUE THREAD

**Issue by llacb47** [AdAway/adaway.github.io#80]
Hi,

please remove these two lines from the hosts file.
```
127.0.0.1 imapi-mu.isnssdk.com
127.0.0.1 imapi-sg.isnssdk.com
```

Blocking these domains prevents direct messages from functioning in the tiktok app. To test this, you will need an account.

**Comment by jawz101** [comment]
removed.  I don't know if any of the other blocks for that domain cause hiccups but I'll leave the rest of them in there for now unless someone speaks up.  Just looking online, I can't really tell who owns that domain and [some of the info](https://i.isnssdk.com/wap/privacy_policy) makes me think I'd want to just handle breakages as people report them.
