### ISSUE TITLE
Update the host request

### ISSUE THREAD

**Issue by Computeitor** [AdAway/adaway.github.io#81]
Hello, 

I apologize if this is not the correct place to post this. I don't have idea. 

I've found the following trackers on an Xiaomi app. Don't know if you can check this and update the hosts file text. 

Facebook Ads:
129com.facebook.ads

Google Ads:
31com.google.android.gms.ads.mediation

Google DoubleClick:
8com.google.android.gms.ads.doubleclick

Regards.

**Comment by jawz101** [comment]
Those don't look like valid top level domains

**Comment by spirillen** [comment]
`.ads` is a very valid TLD <https://www.mypdns.org/w/gtld/.ads/>

But for the more specific domains in question `129com.facebook.ads` then it seems currect there are no valid NS records for it, but that actually doesn't mean there isn't a A|AAAA|DNAME|CNAME record for it. 

But you can obtain the clean valid TLD list here <https://gitlab.com/my-privacy-dns/external-sources/tld/-/blob/master/tld.list> it's originates from <http://data.iana.org/TLD/tlds-alpha-by-domain.txt>

**Comment by jawz101** [comment]
Regardless, they look like Android package or class names so I'm disregarding this
