### ISSUE TITLE
Dynatrace listing

### ISSUE THREAD

**Issue by PerfectSlayer** [AdAway/adaway.github.io#88]
Hello @jawz101 

I received a mail from Dynatrace asking why their company is listed in AdAway hosts file.
Here is the message:

> Hi Bruce,
>
> Hope this e-mail finds you well!
>
> We recently noticed that this GitHub project AdAway has our company listed. I was wondering why that is and what the criteria to list/delist hosts is?
> 
> We are not an ad or user tracking analytics company, we provide application performance monitoring for registered paying customers only.
>
> Our concern is that customers of ours may load AdAway in hopes of blocking ads (a worthy cause! 😊) but may accidentally end up blocking legitimate UI elements and other features of our SaaS product.
> 
> 
> Is there anything we need to do here to get this resolved?
>
> Reference:
> * https://github.com/AdAway/AdAway/wiki/HostsSources
> * https://adaway.org/hosts.txt
> * https://adaway.org/
> 
> **hosts.txt listings**
> ![image](https://user-images.githubusercontent.com/1766222/85025325-8a6f5c80-b177-11ea-9cd4-994471e767b4.png)
> 
> I look forward to your response and please let me know if I missed anything.
> 
> Thank you

I had a quick look to their documentation: https://www.dynatrace.com/support/help/how-to-use-dynatrace/data-privacy-and-security/data-privacy/personal-data-captured-by-dynatrace/
What do you think about it? I let you choose what you want to do about it 😉 
If you need more information, I can ask them by email.

Thanks again!

**Comment by PerfectSlayer** [comment]
EDIT: I might not be urgent. I just reply them and I got the following automatic answer: 

> Thank you for your correspondence.
>
> I am currently out of the office.
> During this time I will have limited access to my emails.
> For immediate assistance please send a message to xxx

😅

**Comment by jawz101** [comment]
just making some notes...

https://reports.exodus-privacy.eu.org/en/trackers/137/

https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/tracking_servers.txt

... I'm going to get rid of most of them except for the one that says it's been seen in Android files via VirusTotal.  I imagine the rest are just pages on their website.

**Comment by spirillen** [comment]
<details><summary>Self note:</summary>
https://www.mypdns.org/T914 and https://www.mypdns.org/rMATRIX98d4d5ef9a1843176061ede57a36745698cc3f1c
</details>

**Comment by Vankog** [comment]
I highly suggest to remove dynatrace from the list.

It is an important monitoring tool for IT Operation of companies. It has nothing to do with user tracking or advertisements.
