### ISSUE TITLE
Remove Tinypass

### ISSUE THREAD

**Issue by itsnotv** [AdAway/adaway.github.io#96]
This prevents me from buying a subscription or logging into my account at https://samharris.org. It looks like they are used for paywall content and not ads. 

```
# [tinypass.com]
127.0.0.1 api.tinypass.com
127.0.0.1 api-v3.tinypass.com
127.0.0.1 buy.tinypass.com
127.0.0.1 cdn.tinypass.com
127.0.0.1 fonts.tinypass.com
127.0.0.1 id.tinypass.com
```

**Comment by jawz101** [comment]
removed.  It's a little bit of a meh decision but I guess it's borderline so I'll get rid of it.  The list is geared toward not only ads, but tracking and anything else that intends to monitor or influence user behavior.  This company makes things to influence purchases and whatnot but I guess it's all based on the user wanting to use a service.
